/**
 * North, West, East & North-East Indian dishes, street food, Indo-Chinese,
 * North-Indian sweets and drinks. Per 100 g (100 ml for drinks); cooked
 * dishes are recipe-standardised home/dhaba estimates (estimate: true).
 */
import type { Row, RowExtra } from "../foods";

type S = [string, number][];
const x = (pop: number, servings: S, src: RowExtra["src"] = "recipe"): RowExtra => ({ pop, servings, src });
/** curry / dal / sabzi in a 150 g katori */
const kat = (pop: number): RowExtra => x(pop, [["½ katori", 75], ["1 large katori", 200], ["100 g", 100]]);
/** dry sabzi / rich dish in a 100 g katori */
const kat100 = (pop: number): RowExtra => x(pop, [["½ katori", 50], ["1 large katori", 150], ["100 g", 100]]);
/** countable: n-piece multiples */
const pc = (pop: number, g: number, word = "pieces"): RowExtra => x(pop, [[`2 ${word}`, g * 2], [`4 ${word}`, g * 4], ["100 g", 100]]);
const plate = (pop: number, g: number): RowExtra => x(pop, [["½ plate", Math.round(g / 2)], ["100 g", 100]]);
const bowl = (pop: number, g: number): RowExtra => x(pop, [["½ bowl", Math.round(g / 2)], ["1 large bowl", Math.round(g * 1.5)], ["100 g", 100]]);
const glass = (pop: number): RowExtra => x(pop, [["1 small glass (150 ml)", 150], ["1 large glass (350 ml)", 350], ["100 ml", 100]]);
const cup = (pop: number, ml: number): RowExtra => x(pop, [["1 small cup", Math.round(ml * 0.6)], ["1 mug", 250], ["100 ml", 100]]);

export const rows: Row[] = [
  /* ---------------- Punjabi & North-Indian home dal ---------------- */
  ["dal-tadka", "Dal tadka", "dal", 115, 5.5, 13.0, 4.5, "1 katori", 150, ["daal tadka", "tadka dal", "dal tarka", "yellow dal tadka", "tadke wali dal", "arhar dal tadka", "dhaba dal tadka", "dal tadka restaurant"], true, "katori", kat(3)],
  ["dal-fry", "Dal fry", "dal", 125, 5.8, 14.0, 5.0, "1 katori", 150, ["daal fry", "dhaba dal fry", "restaurant dal fry", "toor dal fry", "dal fry jeera", "dhal fry", "dall fry"], true, "katori", kat(2)],
  ["maa-ki-dal", "Maa ki dal (whole urad)", "dal", 120, 6.0, 13.0, 5.0, "1 katori", 150, ["maa ki daal", "maah di dal", "kaali dal", "sabut urad dal", "whole urad dal", "dal maa", "maa di dal", "urad dal curry"], true, "katori", kat(1)],
  ["dal-palak", "Dal palak", "dal", 95, 5.0, 11.0, 3.5, "1 katori", 150, ["palak dal", "spinach dal", "dal palak tadka", "palak wali dal", "dal saag"], true, "katori", kat(2)],
  ["panchmel-dal", "Panchmel dal", "dal", 115, 6.0, 14.0, 4.0, "1 katori", 150, ["panchratna dal", "pachmel dal", "five lentil dal", "panchmel daal", "mixed dal"], true, "katori", kat(1)],
  ["lobia-curry", "Lobia (black-eyed beans) curry", "dal", 115, 6.0, 14.0, 4.0, "1 katori", 150, ["lobia", "lobiya", "chawli curry", "rongi", "black eyed beans curry", "chawli usal", "lobia masala"], true, "katori", kat(1)],
  ["kadhi-pakora", "Kadhi pakora", "north", 105, 3.8, 9.0, 6.0, "1 katori", 150, ["kadhi pakoda", "punjabi kadhi", "kadi pakora", "karhi pakora", "kadhi pakode", "besan kadhi", "pakode wali kadhi", "kadi pakoda"], true, "katori", kat(2)],

  /* ---------------- Punjabi & North-Indian sabzi / curries (veg) ---------------- */
  ["sarson-ka-saag", "Sarson ka saag", "north", 100, 3.5, 6.5, 6.5, "1 katori", 150, ["sarson da saag", "sarso ka saag", "mustard greens saag", "sarson saag", "saag punjabi", "sarson ka sag", "sarsoon da saag"], true, "katori", kat(2)],
  ["aloo-matar", "Aloo matar", "north", 105, 2.8, 12.0, 5.0, "1 katori", 150, ["aloo mutter", "alu matar", "matar aloo", "potato peas curry", "aloo matar sabzi", "aloo mattar", "batata vatana"], true, "katori", kat(2)],
  ["jeera-aloo", "Jeera aloo", "north", 120, 2.0, 16.0, 5.5, "1 katori", 100, ["aloo jeera", "zeera aloo", "jira alu", "cumin potatoes", "jeera alu", "aloo jeera fry", "jeera aloo dry"], true, "katori", kat100(2)],
  ["bhindi-masala", "Bhindi masala (onion-tomato)", "north", 120, 2.5, 9.0, 8.0, "1 katori", 100, ["bhindi do pyaza", "okra masala", "bhendi masala", "bhindi masala gravy", "bhindi pyaz", "bhinda nu shaak", "dhaba bhindi"], true, "katori", kat100(2)],
  ["baingan-bharta", "Baingan bharta", "north", 95, 2.0, 8.0, 6.0, "1 katori", 150, ["baingan ka bharta", "bhartha", "brinjal bharta", "begun bharta", "vangyache bharit", "eggplant bharta", "baigan bharta", "ringan no olo", "bharta"], true, "katori", kat(2)],
  ["malai-kofta", "Malai kofta", "north", 195, 5.0, 12.0, 14.0, "1 katori (2 kofta)", 150, ["malai kofta curry", "paneer kofta", "kofta curry", "malai kofte", "veg kofta", "shahi kofta"], true, "katori", kat(2)],
  ["shahi-paneer", "Shahi paneer", "north", 200, 8.0, 8.0, 15.0, "1 katori", 150, ["shahi panir", "paneer shahi", "royal paneer", "shahi paneer gravy", "paneer korma"], true, "katori", kat(2)],
  ["kadai-paneer", "Kadai paneer", "north", 180, 9.0, 7.0, 13.0, "1 katori", 150, ["karahi paneer", "kadhai paneer", "paneer kadai", "kadai panir", "paneer kadhai", "kadhai panir"], true, "katori", kat(2)],
  ["matar-paneer", "Matar paneer", "north", 155, 7.0, 9.0, 10.0, "1 katori", 150, ["mutter paneer", "matar panir", "paneer matar", "peas paneer", "mattar paneer", "paneer mutter"], true, "katori", kat(3)],
  ["paneer-bhurji", "Paneer bhurji", "north", 215, 13.0, 5.0, 16.0, "1 katori", 100, ["panir bhurji", "scrambled paneer", "paneer burji", "paneer bhurjee", "paneer bhurji dry"], true, "katori", kat100(2)],
  ["paneer-tikka-masala", "Paneer tikka masala", "north", 200, 10.0, 7.0, 15.0, "1 katori", 150, ["paneer tikka gravy", "paneer tikka curry", "tikka masala paneer", "paneer lababdar", "paneer makhanwala"], true, "katori", kat(2)],
  ["paneer-do-pyaza", "Paneer do pyaza", "north", 190, 9.0, 7.0, 14.0, "1 katori", 150, ["paneer do pyaaza", "paneer dopyaza", "do pyaza paneer"], true, "katori", kat(1)],
  ["methi-malai-matar", "Methi malai matar", "north", 190, 5.0, 11.0, 14.0, "1 katori", 150, ["methi matar malai", "methi mutter malai", "malai methi matar"], true, "katori", kat(1)],
  ["navratan-korma", "Navratan korma", "north", 180, 4.0, 12.0, 13.0, "1 katori", 150, ["navratna korma", "nav ratan korma", "navrattan korma", "mughlai veg korma"], true, "katori", kat(1)],
  ["veg-jalfrezi", "Veg jalfrezi", "north", 100, 2.0, 9.0, 6.0, "1 katori", 150, ["vegetable jalfrezi", "jalfrezi", "jhalfrezi", "veg jalfraizi"], true, "katori", kat(1)],
  ["veg-kolhapuri", "Veg kolhapuri", "north", 135, 3.0, 10.0, 9.0, "1 katori", 150, ["vegetable kolhapuri", "kolhapuri veg", "kolhapuri sabzi"], true, "katori", kat(1)],
  ["dum-aloo", "Dum aloo (Punjabi)", "north", 135, 2.2, 14.0, 8.0, "1 katori", 150, ["dum alu", "dum aloo punjabi", "dum potato", "dum aaloo", "aloo dum", "dum aloo curry"], true, "katori", kat(2)],
  ["dum-aloo-kashmiri", "Kashmiri dum aloo", "north", 165, 2.5, 14.0, 11.0, "1 katori", 150, ["kashmiri dum aloo", "dum olav", "dum aloo kashmiri", "kashmiri aloo dum"], true, "katori", kat(1)],
  ["pindi-chole", "Pindi chole", "north", 165, 7.0, 18.0, 7.0, "1 katori", 150, ["pindi chana", "rawalpindi chole", "dry chole", "amritsari chole", "pindi chhole", "chole pindi"], true, "katori", kat(2)],
  ["aloo-methi", "Aloo methi", "north", 115, 2.5, 13.0, 6.0, "1 katori", 100, ["methi aloo", "alu methi", "aloo methi sabzi", "methi batata"], true, "katori", kat100(1)],
  ["aloo-palak", "Aloo palak", "north", 90, 2.5, 9.0, 5.0, "1 katori", 150, ["palak aloo", "saag aloo", "alu palak", "spinach potato", "aloo palak sabzi"], true, "katori", kat(1)],
  ["aloo-tamatar", "Aloo tamatar sabzi", "north", 88, 1.8, 11.0, 4.0, "1 katori", 150, ["aloo tamatar", "aloo tamatar ki sabzi", "potato tomato curry", "aloo rassa", "batata rassa"], true, "katori", kat(2)],
  ["aloo-shimla-mirch", "Aloo shimla mirch", "north", 110, 2.0, 12.0, 6.0, "1 katori", 100, ["aloo capsicum", "shimla mirch aloo", "capsicum potato", "alu shimla mirch"], true, "katori", kat100(1)],
  ["gajar-matar", "Gajar matar", "north", 90, 2.5, 10.0, 4.5, "1 katori", 100, ["gajar matar sabzi", "carrot peas", "gajar mutter", "carrot peas sabzi"], true, "katori", kat100(1)],
  ["lauki-sabzi", "Lauki sabzi", "north", 50, 1.0, 4.5, 3.0, "1 katori", 150, ["lauki ki sabzi", "ghiya sabzi", "bottle gourd curry", "dudhi bhaji", "lauki", "doodhi sabzi", "ghiya ki sabzi", "lau ghonto"], true, "katori", kat(2)],
  ["tinda-masala", "Tinda masala", "north", 75, 1.2, 6.0, 5.0, "1 katori", 150, ["tinda", "tinde ki sabzi", "round gourd curry", "tinda sabzi"], true, "katori", kat(1)],
  ["kaddu-sabzi", "Kaddu (pumpkin) sabzi", "north", 75, 1.3, 10.0, 3.5, "1 katori", 150, ["kaddu ki sabzi", "khatta meetha kaddu", "sitaphal sabzi", "pumpkin sabzi", "kaddu", "kashiphal sabzi"], true, "katori", kat(1)],
  ["kathal-sabzi", "Kathal (jackfruit) sabzi", "north", 120, 2.5, 14.0, 6.0, "1 katori", 150, ["kathal ki sabzi", "raw jackfruit curry", "kathal masala", "echor dalna", "kathal curry"], true, "katori", kat(1)],
  ["arbi-fry", "Arbi fry", "north", 160, 2.0, 20.0, 8.0, "1 katori", 100, ["arbi masala", "arvi fry", "colocasia fry", "arbi ki sabzi", "arvi sabzi", "ghuiyan"], true, "katori", kat100(1)],
  ["karela-fry", "Karela fry", "north", 140, 2.5, 10.0, 10.0, "1 katori", 100, ["karele ki sabzi", "bitter gourd fry", "bharwa karela", "karela sabzi", "karela masala", "kareli"], true, "katori", kat100(1)],
  ["soya-chaap", "Soya chaap masala", "north", 195, 12.0, 10.0, 12.0, "1 katori", 150, ["soya chaap", "chaap masala", "soya champ", "soya chap curry", "chaap gravy", "soya chaap curry"], true, "katori", kat(2)],
  ["malai-chaap", "Malai soya chaap (tandoori)", "north", 230, 14.0, 9.0, 15.0, "1 plate (4 sticks)", 150, ["malai chaap", "afghani chaap", "tandoori chaap", "malai soya chaap", "tandoori soya chaap", "achari chaap"], true, "plate", plate(1, 150)],

  /* ---------------- North-Indian breads & breakfasts ---------------- */
  ["makki-di-roti", "Makki di roti", "north", 285, 6.0, 45.0, 9.0, "1 roti", 70, ["makki ki roti", "makke di roti", "maize roti", "corn roti", "makki roti", "makai roti", "makka roti"], true, "piece", pc(2, 70, "rotis")],
  ["missi-roti", "Missi roti", "north", 280, 10.0, 44.0, 7.0, "1 roti", 50, ["besan roti", "missi rotti", "besan ki roti", "missi parantha"], true, "piece", pc(1, 50, "rotis")],
  ["rumali-roti-plain", "Rumali roti", "north", 260, 8.5, 50.0, 3.0, "1 roti", 45, ["roomali", "rumaali roti", "roomaali roti", "handkerchief roti", "rumali rotti"], true, "piece", pc(1, 45, "rotis")],
  ["butter-naan-plain", "Butter naan", "north", 315, 8.0, 46.0, 11.0, "1 naan", 90, ["makhan naan", "butter nan", "naan butter", "butter naans", "makhani naan"], true, "piece", pc(2, 90, "naans")],
  ["garlic-naan-plain", "Garlic naan", "north", 305, 8.0, 46.0, 10.0, "1 naan", 90, ["lahsun naan", "garlic nan", "garlic butter naan", "lasooni naan", "garlic naans"], true, "piece", pc(2, 90, "naans")],
  ["kulcha-plain", "Kulcha (plain)", "north", 290, 8.5, 50.0, 6.0, "1 kulcha", 80, ["plain kulcha", "kulche", "maida kulcha", "kulchas", "butter kulcha"], true, "piece", pc(1, 80, "kulchas")],
  ["amritsari-kulcha", "Amritsari aloo kulcha", "north", 285, 7.0, 42.0, 10.0, "1 kulcha", 120, ["amritsari kulcha", "aloo kulcha", "stuffed kulcha", "amritsari naan", "paneer kulcha", "masala kulcha"], true, "piece", pc(2, 120, "kulchas")],
  ["methi-thepla", "Methi thepla", "north", 300, 8.0, 42.0, 11.0, "1 thepla", 40, ["theplas", "methi na thepla", "gujarati thepla", "thepala", "methi thepala", "dudhi thepla"], true, "piece", pc(2, 40, "theplas")],
  ["methi-paratha", "Methi paratha", "north", 275, 6.5, 38.0, 11.0, "1 paratha", 70, ["methi parantha", "fenugreek paratha", "methi ka paratha", "methi parotha"], true, "piece", pc(2, 70, "parathas")],
  ["mooli-paratha", "Mooli paratha", "north", 245, 5.5, 35.0, 9.0, "1 paratha", 110, ["muli paratha", "radish paratha", "mooli parantha", "mooli ka paratha", "muli parantha"], true, "piece", pc(2, 110, "parathas")],
  ["onion-paratha", "Onion (pyaz) paratha", "north", 260, 6.0, 37.0, 10.0, "1 paratha", 100, ["pyaz paratha", "onion parantha", "pyaaz paratha", "kanda paratha", "pyaz ka paratha"], true, "piece", pc(1, 100, "parathas")],
  ["gobi-paratha", "Gobi paratha", "north", 230, 5.5, 32.0, 9.0, "1 paratha", 120, ["gobhi paratha", "cauliflower paratha", "gobi parantha", "phool gobhi paratha"], true, "piece", pc(2, 120, "parathas")],
  ["pudina-paratha", "Pudina paratha", "north", 295, 6.5, 40.0, 12.0, "1 paratha", 70, ["mint paratha", "pudina parantha", "pudina lachha paratha"], true, "piece", pc(1, 70, "parathas")],
  ["palak-paratha", "Palak paratha", "north", 270, 6.5, 38.0, 10.0, "1 paratha", 70, ["spinach paratha", "palak parantha", "palak ka paratha"], true, "piece", pc(1, 70, "parathas")],
  ["dal-paratha", "Dal paratha", "north", 275, 8.0, 38.0, 10.0, "1 paratha", 90, ["daal paratha", "chana dal paratha", "dal parantha", "moong dal paratha", "dal puri paratha"], true, "piece", pc(1, 90, "parathas")],
  ["egg-paratha", "Egg (anda) paratha", "egg", 255, 9.0, 28.0, 12.0, "1 paratha", 130, ["anda paratha", "egg parantha", "ande ka paratha", "egg stuffed paratha", "anda parantha"], true, "piece", pc(1, 130, "parathas")],
  ["keema-paratha", "Keema paratha", "nonveg", 265, 11.0, 28.0, 12.0, "1 paratha", 130, ["qeema paratha", "mutton keema paratha", "kheema paratha", "keema parantha", "chicken keema paratha"], true, "piece", pc(1, 130, "parathas")],
  ["bedmi-puri", "Bedmi puri", "north", 340, 7.0, 40.0, 17.0, "1 puri", 40, ["bedmi poori", "bedai puri", "bedmi aloo", "urad dal puri", "bedmi"], true, "piece", pc(1, 40, "puris")],
  ["veg-dalia", "Vegetable dalia (savoury)", "breakfast", 110, 3.5, 18.0, 2.5, "1 bowl", 200, ["dalia", "daliya", "namkeen dalia", "broken wheat upma", "dalia khichdi", "godhuma rava upma", "lapsi upma"], true, "bowl", bowl(2, 200)],
  ["sweet-dalia", "Sweet dalia (with milk)", "breakfast", 105, 3.8, 17.0, 2.6, "1 bowl", 200, ["meetha dalia", "dalia with milk", "milk dalia", "doodh dalia", "broken wheat porridge"], true, "bowl", bowl(1, 200)],

  ["dhaba-chicken", "Dhaba chicken curry (Punjabi)", "nonveg", 180, 14.0, 4.0, 12.0, "1 katori", 150, ["dhaba style chicken", "punjabi chicken curry", "desi chicken curry", "dhabe wala chicken", "chicken rara"], true, "katori", kat(2)],
  ["bhuna-gosht", "Bhuna gosht", "nonveg", 215, 16.0, 4.0, 15.0, "1 katori", 150, ["bhuna mutton", "mutton bhuna", "bhuna gosht masala", "dry mutton masala", "mutton bhuna masala"], true, "katori", kat(1)],
  ["hara-bhara-kebab", "Hara bhara kebab", "snack", 180, 5.0, 18.0, 10.0, "1 kebab", 35, ["hara bhara kabab", "harabhara kebab", "veg green kebab", "spinach peas kebab", "hara bara kebab"], true, "piece", pc(1, 35, "kebabs")],
  ["dahi-kebab", "Dahi ke kebab", "snack", 225, 8.0, 15.0, 15.0, "1 kebab", 35, ["dahi kebab", "dahi ke kabab", "hung curd kebab", "curd kebab", "dahi kabab"], true, "piece", pc(0, 35, "kebabs")],

  /* ---------------- Mughlai, Awadhi, Punjabi non-veg ---------------- */
  ["chicken-korma", "Chicken korma (Mughlai)", "nonveg", 200, 14.0, 5.0, 14.0, "1 katori", 150, ["murgh korma", "shahi chicken korma", "chicken qorma", "mughlai chicken korma", "white chicken korma", "chicken shahi korma"], true, "katori", kat(2)],
  ["mutton-korma", "Mutton korma", "nonveg", 220, 15.0, 4.5, 16.0, "1 katori", 150, ["gosht korma", "mutton qorma", "shahi mutton korma", "lamb korma", "mughlai mutton korma"], true, "katori", kat(1)],
  ["rogan-josh", "Mutton rogan josh", "nonveg", 195, 15.0, 4.0, 13.0, "1 katori", 150, ["rogan gosht", "roghan josh", "mutton rogan josh", "kashmiri rogan josh", "lamb rogan josh", "rogan josh", "rogan josh mutton"], true, "katori", kat(2)],
  ["nihari", "Nihari (mutton)", "nonveg", 195, 13.0, 4.0, 14.0, "1 katori", 200, ["nahari", "mutton nihari", "nalli nihari", "nihari gosht", "nehari", "nalli nahari"], true, "katori", kat(1)],
  ["laal-maas", "Laal maas", "nonveg", 205, 15.0, 3.0, 15.0, "1 katori", 150, ["lal maas", "laal maans", "rajasthani mutton", "lal maans", "laal mass"], true, "katori", kat(1)],
  ["yakhni", "Mutton yakhni (Kashmiri)", "nonveg", 160, 13.0, 4.0, 10.0, "1 katori", 150, ["kashmiri yakhni", "yakhini", "mutton yakhni", "yakhni gosht", "dahi gosht"], true, "katori", kat(1)],
  ["gushtaba", "Gushtaba", "nonveg", 210, 13.0, 4.0, 16.0, "1 katori (2 balls)", 150, ["goshtaba", "gustaba", "kashmiri gushtaba", "rista", "kashmiri meatball curry"], true, "katori", kat(0)],
  ["mutton-keema", "Mutton keema", "nonveg", 205, 15.0, 5.0, 14.0, "1 katori", 150, ["keema", "kheema", "qeema", "mutton kheema", "keema masala", "kheema masala", "minced mutton curry", "kothu kari"], true, "katori", kat(2)],
  ["keema-matar", "Keema matar", "nonveg", 190, 13.0, 7.0, 12.0, "1 katori", 150, ["kheema matar", "keema mutter", "matar keema", "mutton keema peas", "qeema matar"], true, "katori", kat(1)],
  ["chicken-keema", "Chicken keema", "nonveg", 160, 16.0, 4.0, 9.0, "1 katori", 150, ["chicken kheema", "chicken mince curry", "chicken keema masala", "chicken qeema"], true, "katori", kat(2)],
  ["kheema-pav", "Kheema pav", "nonveg", 220, 10.0, 22.0, 10.0, "1 plate (2 pav)", 280, ["keema pav", "keema pao", "kheema pao", "mutton keema pav", "kheema pav plate"], true, "plate", plate(1, 280)],
  ["chicken-changezi", "Chicken changezi", "nonveg", 210, 14.0, 5.0, 15.0, "1 katori", 150, ["changezi chicken", "chicken changeji", "murgh changezi", "changezi"], true, "katori", kat(1)],
  ["kadai-chicken", "Kadai chicken", "nonveg", 180, 15.0, 5.0, 11.0, "1 katori", 150, ["karahi chicken", "chicken kadai", "kadhai chicken", "chicken karahi", "kadai murgh"], true, "katori", kat(2)],
  ["chicken-do-pyaza", "Chicken do pyaza", "nonveg", 170, 14.0, 6.0, 10.0, "1 katori", 150, ["chicken do pyaaza", "murgh do pyaza", "chicken dopiaza"], true, "katori", kat(1)],
  ["chicken-handi", "Chicken handi", "nonveg", 185, 14.0, 5.0, 12.0, "1 katori", 150, ["handi chicken", "murgh handi", "chicken handi masala", "dum chicken"], true, "katori", kat(1)],
  ["chicken-saagwala", "Palak chicken (saagwala)", "nonveg", 160, 14.0, 4.0, 10.0, "1 katori", 150, ["palak chicken", "chicken saagwala", "saag chicken", "chicken palak", "murgh saagwala"], true, "katori", kat(1)],
  ["murgh-musallam", "Murgh musallam", "nonveg", 205, 16.0, 4.0, 14.0, "1 katori", 200, ["murg musallam", "chicken musallam", "musallam"], true, "katori", kat(0)],
  ["tangdi-kebab", "Chicken tangdi kebab", "nonveg", 185, 22.0, 2.0, 10.0, "1 piece", 80, ["tangri kebab", "tangdi kabab", "murgh tangdi", "chicken leg kebab", "tangdi kebab tandoori"], true, "piece", pc(1, 80)],
  ["hariyali-tikka", "Hariyali chicken tikka", "nonveg", 175, 20.0, 3.0, 9.0, "6 pieces", 150, ["hariyali kebab", "green chicken tikka", "hara bhara chicken tikka", "hariyali murgh tikka", "hariyali tikka"], true, "plate", plate(1, 150)],
  ["reshmi-kebab-plate", "Reshmi kebab (murgh)", "nonveg", 200, 20.0, 3.0, 12.0, "1 plate (6 pieces)", 150, ["murgh reshmi", "reshmi kabab", "chicken reshmi tikka", "reshmi tikka", "chicken reshmi kebab"], true, "plate", plate(1, 150)],
  ["malai-kebab-chicken", "Chicken malai tikka", "nonveg", 215, 19.0, 3.0, 14.0, "1 plate (6 pieces)", 150, ["murgh malai tikka", "afghani chicken", "chicken malai kebab", "malai tikka chicken", "afghani tikka"], true, "plate", plate(2, 150)],
  ["mutton-seekh-kebab", "Mutton seekh kebab", "nonveg", 235, 17.0, 4.0, 17.0, "1 seekh", 50, ["sheekh kabab", "mutton seekh", "seek kebab", "seekh kabab mutton", "kakori kebab", "lamb seekh kebab"], true, "piece", pc(2, 50, "seekhs")],
  ["galouti-kebab", "Galouti kebab", "nonveg", 255, 15.0, 8.0, 18.0, "1 kebab", 35, ["galawati kebab", "galauti", "lucknowi galouti", "tunday kebab", "galouti kabab", "galauti kabab"], true, "piece", pc(1, 35, "kebabs")],
  ["shami-kebab", "Shami kebab", "nonveg", 210, 16.0, 10.0, 12.0, "1 kebab", 45, ["shami kabab", "mutton shami kebab", "shammi kebab", "chicken shami kebab", "shami tikki"], true, "piece", pc(2, 45, "kebabs")],
  ["boti-kebab", "Mutton boti kebab", "nonveg", 200, 20.0, 3.0, 12.0, "1 plate (6 pieces)", 150, ["boti kabab", "mutton boti", "boti tikka", "gosht boti kebab"], true, "plate", plate(1, 150)],
  ["fish-tikka", "Fish tikka", "nonveg", 165, 20.0, 3.0, 8.0, "1 plate (6 pieces)", 150, ["tandoori fish", "fish tikka tandoori", "machhi tikka", "mahi tikka", "fish tandoori"], true, "plate", plate(1, 150)],
  ["amritsari-fish", "Amritsari fish fry", "nonveg", 210, 17.0, 9.0, 12.0, "1 plate", 150, ["amritsari machhi", "amritsari fish", "batter fried fish punjabi", "amritsari fish pakora", "fish pakora"], true, "plate", plate(1, 150)],
  ["mughlai-paratha", "Mughlai paratha (egg)", "egg", 285, 10.0, 25.0, 16.0, "1 paratha", 200, ["moglai porota", "moghlai paratha", "mughlai porota", "egg mughlai paratha", "keema mughlai paratha"], true, "piece", x(1, [["½ paratha", 100], ["100 g", 100]])],
  ["sheermal", "Sheermal", "north", 330, 8.0, 52.0, 10.0, "1 sheermal", 70, ["shirmal", "sheermaal", "saffron naan", "sheermal roti"], true, "piece", pc(0, 70)],
  ["lucknowi-biryani", "Lucknowi (Awadhi) biryani", "nonveg", 185, 8.5, 22.0, 7.0, "1 plate", 300, ["awadhi biryani", "dum pukht biryani", "lucknow biryani", "lucknowi mutton biryani", "awadhi mutton biryani", "lucknowi chicken biryani"], true, "plate", plate(1, 300)],
  ["kolkata-biryani", "Kolkata biryani (with aloo & egg)", "nonveg", 190, 7.5, 24.0, 7.0, "1 plate", 350, ["calcutta biryani", "kolkata mutton biryani", "kolkata chicken biryani", "aloo biryani", "kolkata style biryani", "arsalan biryani"], true, "plate", plate(1, 350)],
  ["yakhni-pulao", "Chicken yakhni pulao", "nonveg", 185, 9.0, 22.0, 7.0, "1 plate", 300, ["chicken pulao", "yakhni pulao", "mutton pulao", "chicken pulav", "yakhni pulav", "murgh pulao"], true, "plate", plate(1, 300)],
  ["matar-pulao", "Matar pulao", "rice", 165, 3.5, 27.0, 5.0, "1 cup", 180, ["matar pulav", "green peas pulao", "mutter pulao", "matar chawal", "vatana bhaat"], true, "cup", x(1, [["½ cup", 90], ["1 plate", 300], ["100 g", 100]])],
  ["kashmiri-pulao", "Kashmiri pulao", "rice", 210, 4.0, 30.0, 8.0, "1 cup", 180, ["kashmiri pulav", "kesar pulao", "dry fruit pulao", "sweet pulao", "mewa pulao"], true, "cup", x(1, [["½ cup", 90], ["1 plate", 300], ["100 g", 100]])],

  ["tehri", "Tehri (UP veg pulao)", "rice", 155, 3.0, 24.0, 5.0, "1 cup", 180, ["tahari", "tehari", "tahri", "veg tehri", "aloo matar tehri"], true, "cup", x(1, [["½ cup", 90], ["1 plate", 300], ["100 g", 100]])],
  ["kadai-mushroom", "Kadai mushroom", "north", 110, 3.0, 7.0, 8.0, "1 katori", 150, ["kadhai mushroom", "mushroom kadai", "karahi mushroom", "mushroom do pyaza", "matar mushroom"], true, "katori", kat(1)],
  ["urad-dal-dhuli", "Dhuli urad dal", "dal", 108, 6.0, 13.0, 3.5, "1 katori", 150, ["dhuli urad", "white urad dal", "safed urad dal", "urad dal dry", "sukhi urad dal", "mah di dal dhuli"], true, "katori", kat(1)],
  ["haak-saag", "Haak saag (Kashmiri)", "north", 75, 2.5, 5.0, 5.0, "1 katori", 150, ["haak", "kashmiri haak", "collard greens kashmiri", "haakh", "monji haak"], true, "katori", kat(0)],
  ["paneer-pakora", "Paneer pakora", "snack", 260, 10.0, 15.0, 18.0, "1 piece", 30, ["paneer pakoda", "paneer bhajji", "paneer fritters", "paneer pakode", "paneer bajji"], true, "piece", pc(2, 30)],

  /* ---------------- Rajasthani ---------------- */
  ["dal-baati-churma", "Dal baati churma (plate)", "north", 245, 6.0, 30.0, 11.0, "1 plate (2 baati)", 400, ["dal baati churma", "dal bati churma", "dal bati", "daal baati", "dal baati plate", "rajasthani thali dal baati"], true, "plate", plate(2, 400)],
  ["baati", "Baati (with ghee)", "north", 380, 8.0, 55.0, 14.0, "1 baati", 70, ["bati", "bafla", "baafla", "ghee baati", "masala baati", "baatis"], true, "piece", pc(1, 70, "baatis")],
  ["churma", "Churma", "sweet", 440, 6.0, 55.0, 22.0, "1 katori", 80, ["churma ladoo", "churma laddu", "rajasthani churma", "gud churma", "wheat churma"], true, "katori", x(1, [["2 tbsp", 30], ["1 large katori", 120], ["100 g", 100]])],
  ["gatte-ki-sabzi", "Gatte ki sabzi", "north", 145, 6.0, 12.0, 8.0, "1 katori", 150, ["gatte ki sabji", "gatta curry", "besan gatte", "gatte ka saag", "gatte", "besan gatta curry"], true, "katori", kat(1)],
  ["ker-sangri", "Ker sangri", "north", 170, 5.0, 15.0, 10.0, "1 katori", 100, ["kair sangri", "ker sangri sabzi", "sangri", "ker sangri ki sabzi"], true, "katori", kat100(0)],
  ["mirchi-vada", "Mirchi vada (Jodhpuri)", "snack", 275, 5.0, 28.0, 16.0, "1 mirchi vada", 80, ["jodhpuri mirchi vada", "mirchi bada", "mirchi wada", "stuffed mirchi pakoda", "mirchi vade"], true, "piece", pc(1, 80)],
  ["pyaaz-kachori", "Pyaaz kachori", "snack", 410, 6.0, 40.0, 25.0, "1 kachori", 70, ["pyaz kachori", "onion kachori", "jodhpuri pyaz kachori", "pyaj kachori", "kanda kachori"], true, "piece", pc(2, 70, "kachoris")],
  ["ghevar", "Ghevar", "sweet", 440, 5.0, 48.0, 25.0, "1 piece", 80, ["malai ghevar", "rabri ghevar", "ghewar", "mawa ghevar"], true, "piece", x(1, [["½ piece", 40], ["100 g", 100]])],

  /* ---------------- Gujarati ---------------- */
  ["khandvi", "Khandvi", "snack", 185, 8.0, 18.0, 9.0, "1 plate (6 rolls)", 100, ["khandavi", "suralichi vadi", "patuli", "khandvi rolls", "gujarati khandvi"], true, "plate", plate(1, 100)],
  ["handvo", "Handvo", "snack", 200, 7.0, 25.0, 8.0, "1 piece", 100, ["handwa", "handvo cake", "dudhi handvo", "gujarati handvo", "mixed dal handvo"], true, "piece", pc(1, 100)],
  ["undhiyu", "Undhiyu", "north", 170, 4.0, 14.0, 11.0, "1 katori", 150, ["undhiya", "oondhiyu", "surti undhiyu", "undhyu", "undhiyoo"], true, "katori", kat(1)],
  ["fafda", "Fafda", "snack", 480, 12.0, 45.0, 28.0, "1 plate", 100, ["fafada", "fafda gathiya", "fafda jalebi", "fafdaa", "papdi gathiya"], true, "plate", x(1, [["5 strips", 50], ["100 g", 100]])],
  ["jalebi", "Jalebi", "sweet", 385, 2.5, 60.0, 15.0, "1 piece", 25, ["jilebi", "jalebis", "jilapi", "jalebi plate", "jilbi", "zalebi", "garma garam jalebi"], true, "piece", x(2, [["2 pieces", 50], ["1 plate (100 g)", 100], ["4 pieces", 100]])],
  ["imarti", "Imarti", "sweet", 385, 4.0, 58.0, 15.0, "1 piece", 40, ["amriti", "imirti", "jhangri", "jangri", "imartee"], true, "piece", pc(1, 40)],
  ["khakhra", "Khakhra", "snack", 400, 11.0, 65.0, 10.5, "1 khakhra", 15, ["khakra", "methi khakhra", "jeera khakhra", "masala khakhra", "khakhras", "khakharaa"], true, "piece", pc(1, 15, "khakhras")],
  ["sev-tameta", "Sev tameta nu shaak", "north", 135, 3.0, 10.0, 9.0, "1 katori", 150, ["sev tamatar", "sev tameta", "sev tamatar ki sabzi", "sev tameta shaak", "sev tomato curry"], true, "katori", kat(1)],
  ["dal-dhokli", "Dal dhokli", "dal", 135, 5.0, 20.0, 4.0, "1 bowl", 250, ["daal dhokli", "dal dhokali", "varan phal", "chakolya", "dal dhokri"], true, "bowl", bowl(1, 250)],
  ["gujarati-kadhi", "Gujarati kadhi", "dal", 65, 2.5, 7.0, 3.0, "1 katori", 150, ["sweet kadhi", "khatti meethi kadhi", "gujarati kadi", "kadhi gujarati", "dahi ni kadhi"], true, "katori", kat(1)],
  ["gujarati-dal", "Gujarati dal (khatti meethi)", "dal", 72, 3.5, 10.0, 2.0, "1 katori", 150, ["gujarati daal", "khatti meethi dal", "gujarati toor dal", "gujrati dal", "gujarati dal sweet"], true, "katori", kat(1)],
  ["muthiya", "Muthiya (steamed)", "snack", 200, 6.0, 28.0, 7.0, "1 plate", 100, ["muthia", "dudhi muthiya", "methi muthiya", "lauki muthiya", "muthiyas", "muthiye"], true, "plate", plate(1, 100)],
  ["patra", "Patra (alu vadi)", "snack", 210, 5.0, 25.0, 10.0, "1 piece", 25, ["paatra", "alu vadi", "aloo wadi", "colocasia rolls", "arbi patta rolls", "patra rolls", "alu wadi"], true, "piece", pc(1, 25)],
  ["sev-usal", "Sev usal", "snack", 200, 7.0, 20.0, 10.0, "1 plate", 250, ["sev usal vadodara", "sev usal plate", "usal sev", "ragda sev"], true, "plate", plate(1, 250)],
  ["lilva-kachori", "Lilva kachori", "snack", 325, 6.0, 35.0, 18.0, "1 kachori", 40, ["lilva kachori gujarati", "tuvar lilva kachori", "green peas kachori", "matar kachori"], true, "piece", pc(1, 40, "kachoris")],
  ["methi-gota", "Methi na gota", "snack", 320, 8.0, 32.0, 18.0, "1 plate", 100, ["methi gota", "methi na bhajiya", "methi pakoda", "methi bhaji", "dakor na gota"], true, "plate", plate(1, 100)],
  ["sev-khamani", "Sev khamani", "snack", 245, 9.0, 25.0, 12.0, "1 plate", 150, ["sev khaman", "amiri khaman", "khamani", "surti sev khamani"], true, "plate", plate(1, 150)],
  ["mohanthal", "Mohanthal", "sweet", 450, 6.0, 50.0, 25.0, "1 piece", 40, ["mohan thal", "besan barfi", "mohanthaal", "besan chakki"], true, "piece", pc(1, 40)],

  /* ---------------- Maharashtrian ---------------- */
  ["misal-pav", "Misal pav", "breakfast", 175, 6.0, 20.0, 8.0, "1 plate (2 pav)", 350, ["misal", "missal pav", "puneri misal", "kolhapuri misal", "misal pao", "nashik misal", "misal plate"], true, "plate", x(2, [["Misal only (1 bowl)", 250], ["½ plate", 175], ["100 g", 100]])],
  ["matki-usal", "Matki usal", "north", 135, 7.0, 16.0, 5.0, "1 katori", 150, ["matki chi usal", "moth bean usal", "usal", "sprouts usal", "mataki usal", "moth curry"], true, "katori", kat(1)],
  ["sabudana-khichdi", "Sabudana khichdi", "breakfast", 220, 2.5, 35.0, 8.0, "1 cup", 150, ["sabudana khichadi", "sago khichdi", "sabudana kichdi", "javvarisi upma", "saboodana khichdi", "fasting khichdi", "vrat khichdi"], true, "cup", x(2, [["½ cup", 75], ["1 plate", 250], ["100 g", 100]])],
  ["sabudana-vada", "Sabudana vada", "snack", 280, 3.0, 35.0, 14.0, "1 vada", 45, ["sabudana wada", "sago vada", "sabudana vade", "javvarisi vadai", "saboodana vada", "vrat vada"], true, "piece", pc(2, 45, "vadas")],
  ["thalipeeth", "Thalipeeth", "breakfast", 275, 8.0, 38.0, 10.0, "1 thalipeeth", 80, ["thalipith", "bhajani thalipeeth", "thalipeeth bhajani", "thalipit", "sabudana thalipeeth"], true, "piece", pc(1, 80)],
  ["zunka", "Zunka", "north", 170, 8.0, 14.0, 9.0, "1 katori", 100, ["jhunka", "besan zunka", "zunka bhakar", "zunka bhakri", "jhunka bhakar"], true, "katori", kat100(1)],
  ["pithla", "Pithla", "north", 90, 5.0, 9.0, 4.0, "1 katori", 150, ["pitla", "pithale", "pithla bhakri", "besan pithla", "pithle"], true, "katori", kat(1)],
  ["amti", "Amti (Maharashtrian dal)", "dal", 90, 4.5, 11.0, 3.0, "1 katori", 150, ["katachi amti", "maharashtrian dal", "varan", "toor dal amti", "amti dal", "varan bhaat dal"], true, "katori", kat(1)],
  ["bharli-vangi", "Bharli vangi", "north", 145, 2.5, 9.0, 11.0, "1 katori", 150, ["bharleli vangi", "stuffed brinjal maharashtrian", "bharwa baingan", "masala vangi", "stuffed baingan"], true, "katori", kat(1)],
  ["masale-bhat", "Masale bhat", "rice", 170, 3.5, 25.0, 6.0, "1 cup", 180, ["masala bhat", "maharashtrian masale bhaat", "vangi bhaat", "masale bhaat", "tondli bhat"], true, "cup", x(1, [["½ cup", 90], ["1 plate", 300], ["100 g", 100]])],
  ["kolhapuri-chicken", "Kolhapuri chicken", "nonveg", 190, 15.0, 5.0, 12.0, "1 katori", 150, ["chicken kolhapuri", "kolhapuri chicken curry", "kombdi rassa", "chicken tambda rassa"], true, "katori", kat(1)],
  ["tambda-rassa", "Tambda rassa (mutton)", "nonveg", 180, 14.0, 4.0, 12.0, "1 katori", 150, ["kolhapuri mutton", "mutton tambda rassa", "tambda", "mutton kolhapuri", "kolhapuri mutton rassa"], true, "katori", kat(1)],
  ["pandhra-rassa", "Pandhra rassa", "nonveg", 75, 6.0, 2.0, 5.0, "1 bowl", 200, ["pandhra", "white rassa", "pandhara rassa", "kolhapuri white curry"], true, "bowl", bowl(0, 200)],
  ["modak", "Ukadiche modak", "sweet", 250, 3.0, 42.0, 8.0, "1 modak", 40, ["modak", "ukadiche modak", "steamed modak", "modakam", "modhak", "talniche modak", "fried modak"], true, "piece", pc(1, 40, "modaks")],
  ["kothimbir-vadi", "Kothimbir vadi", "snack", 260, 8.0, 25.0, 14.0, "1 piece", 30, ["kothimbir wadi", "coriander vadi", "kothmir vadi", "kothambir vadi", "kothimbeer vadi"], true, "piece", pc(1, 30)],
  ["bhakarwadi", "Bhakarwadi", "snack", 460, 8.0, 50.0, 25.0, "5 pieces", 40, ["bakarwadi", "bhakarvadi", "chitale bhakarwadi", "bhakar wadi", "bakarvadi"], true, "serving", x(1, [["1 piece", 8], ["10 pieces", 80], ["100 g", 100]])],
  ["poha-chivda", "Poha chivda", "snack", 480, 9.0, 55.0, 25.0, "1 small bowl", 30, ["chivda poha", "chiwda", "nylon poha chivda", "makai chivda", "diwali chivda", "patal pohe chivda"], true, "serving", x(1, [["1 handful", 25], ["1 bowl", 60], ["100 g", 100]])],
  ["shrikhand", "Shrikhand", "sweet", 240, 6.0, 38.0, 7.0, "1 katori", 100, ["amrakhand", "kesar shrikhand", "elaichi shrikhand", "mango shrikhand", "shreekhand", "srikhand"], true, "katori", x(1, [["2 tbsp", 40], ["½ katori", 50], ["100 g", 100]])],
  ["basundi", "Basundi", "sweet", 205, 6.0, 25.0, 9.0, "1 katori", 100, ["basundhi", "sitaphal basundi", "basundi sweet", "rabdi basundi"], true, "katori", kat100(1)],
  ["aamras", "Aamras", "sweet", 80, 0.8, 18.0, 0.4, "1 katori", 150, ["aam ras", "mango pulp", "amras", "keri no ras", "mango ras"], true, "katori", kat(1)],
  ["pav-plain", "Ladi pav", "bread", 270, 8.5, 50.0, 4.0, "1 pav", 40, ["ladi pao", "pav bread", "pao", "pav buns", "laadi pav", "pav pieces"], true, "piece", pc(2, 40, "pav")],
  ["bun-maska", "Bun maska", "bread", 345, 7.0, 48.0, 14.0, "1 bun maska", 80, ["maska bun", "bun maska pav", "brun maska", "bun malai", "maska pav"], true, "piece", pc(1, 80)],
  ["masala-pav", "Masala pav", "fastfood", 290, 6.0, 40.0, 12.0, "1 plate (2 pav)", 140, ["masala pao", "pav masala", "bombay masala pav", "butter masala pav"], true, "plate", plate(1, 140)],
  ["sol-kadhi", "Sol kadhi", "drink", 60, 1.0, 5.0, 4.0, "1 glass", 200, ["solkadhi", "sol kadi", "kokum kadhi", "kokum coconut drink", "solkadi"], true, "glass", glass(1)],

  ["shev-bhaji", "Shev bhaji (Khandeshi)", "north", 175, 5.0, 12.0, 12.0, "1 katori", 150, ["sev bhaji", "khandeshi shev bhaji", "shev bhaaji", "sev curry", "shev chi bhaji"], true, "katori", kat(0)],

  /* ---------------- Bengali, Odia, Assamese, North-East ---------------- */
  ["machher-jhol", "Machher jhol (Bengali fish curry)", "nonveg", 115, 12.0, 3.0, 6.0, "1 katori", 150, ["macher jhol", "maacher jhol", "bengali fish curry", "rohu curry", "rui macher jhol", "machh jhol", "maach jhol", "katla curry"], true, "katori", kat(2)],
  ["shorshe-ilish", "Shorshe ilish (hilsa in mustard)", "nonveg", 225, 15.0, 3.0, 17.0, "1 katori (1 piece)", 120, ["sorshe ilish", "hilsa mustard curry", "ilish bhapa", "bhapa ilish", "ilish macher jhal", "hilsa curry", "ilish maach"], true, "katori", kat100(1)],
  ["chingri-malai-curry", "Chingri malai curry", "nonveg", 190, 11.0, 5.0, 14.0, "1 katori", 150, ["chingri malaikari", "prawn malai curry", "chingri malai", "malai chingri", "prawn malaikari"], true, "katori", kat(1)],
  ["doi-maach", "Doi maach", "nonveg", 150, 13.0, 4.0, 9.0, "1 katori", 150, ["doi machh", "dahi fish curry", "doi mach", "curd fish curry", "doi rui"], true, "katori", kat(1)],
  ["kosha-mangsho", "Kosha mangsho", "nonveg", 215, 15.0, 5.0, 15.0, "1 katori", 150, ["kosha mangso", "mutton kosha", "bengali mutton curry", "golbari kosha mangsho", "kasha mangsho", "mangshor jhol"], true, "katori", kat(1)],
  ["chicken-kosha", "Chicken kosha", "nonveg", 190, 16.0, 5.0, 12.0, "1 katori", 150, ["kosha chicken", "murgir kosha", "bengali chicken curry", "murgir jhol"], true, "katori", kat(1)],
  ["masor-tenga", "Masor tenga (Assamese sour fish)", "nonveg", 105, 12.0, 3.0, 5.0, "1 katori", 150, ["masor tenga", "assamese fish curry", "tenga fish", "machor tenga", "masor tenga tomato"], true, "katori", kat(0)],
  ["pork-bamboo-shoot", "Pork with bamboo shoot (North-East)", "nonveg", 230, 14.0, 3.0, 18.0, "1 katori", 150, ["naga pork", "pork bamboo shoot", "smoked pork bamboo shoot", "pork with axone", "pork curry naga"], true, "katori", kat(0)],
  ["luchi", "Luchi", "bread", 370, 6.5, 45.0, 18.0, "1 luchi", 20, ["loochi", "bengali puri", "maida puri", "luchis", "luchi aloo"], true, "piece", pc(2, 20, "luchis")],
  ["aloo-posto", "Aloo posto", "north", 160, 4.0, 14.0, 10.0, "1 katori", 100, ["alu posto", "aloo posta", "potato poppy seed curry", "posto aloo", "aloo khus khus"], true, "katori", kat100(1)],
  ["shukto", "Shukto", "north", 100, 3.0, 9.0, 6.0, "1 katori", 150, ["sukto", "bengali shukto", "shukto torkari", "shukta"], true, "katori", kat(0)],
  ["begun-bhaja", "Begun bhaja", "snack", 150, 2.0, 8.0, 12.0, "1 slice", 40, ["baingan bhaja", "brinjal fry bengali", "begun bhaja slice", "baingan fry slices"], true, "piece", pc(1, 40, "slices")],
  ["cholar-dal", "Cholar dal", "dal", 155, 7.0, 18.0, 6.0, "1 katori", 150, ["chholar dal", "bengali chana dal", "cholar daal", "narkel cholar dal"], true, "katori", kat(1)],
  ["ghugni", "Ghugni", "snack", 145, 7.0, 18.0, 5.0, "1 katori", 150, ["ghughni", "ghugni chaat", "yellow peas curry", "matar ghugni", "dried peas curry"], true, "katori", kat(1)],
  ["bhoger-khichuri", "Bhoger khichuri", "rice", 120, 4.0, 17.0, 4.0, "1 cup", 200, ["khichuri", "bengali khichuri", "bhuni khichuri", "bhog khichdi", "moong dal khichuri"], true, "cup", x(1, [["½ cup", 100], ["1 plate", 300], ["100 g", 100]])],
  ["basanti-pulao", "Basanti pulao", "rice", 205, 3.5, 32.0, 7.0, "1 cup", 150, ["mishti pulao", "basonti pulao", "bengali sweet pulao", "basanti polao", "mishti polao"], true, "cup", x(1, [["½ cup", 75], ["1 plate", 250], ["100 g", 100]])],
  ["dalma", "Dalma (Odia)", "dal", 100, 5.0, 13.0, 3.0, "1 katori", 150, ["odia dalma", "dalma odisha", "vegetable dalma", "dalama"], true, "katori", kat(0)],
  ["pakhala", "Pakhala bhata", "rice", 90, 2.0, 20.0, 0.5, "1 bowl", 350, ["pakhala", "pakhal", "panta bhat", "poita bhat", "dahi pakhala", "fermented rice water rice"], true, "bowl", bowl(0, 350)],
  ["thukpa", "Thukpa", "fastfood", 90, 5.0, 12.0, 2.5, "1 bowl", 350, ["chicken thukpa", "veg thukpa", "tibetan noodle soup", "thukpa soup", "thenthuk"], true, "bowl", bowl(1, 350)],

  ["aloo-pitika", "Aloo pitika (Assamese mash)", "veg", 115, 2.0, 15.0, 5.0, "1 katori", 100, ["alu pitika", "aloo bhorta", "alu bhate", "aloo makha", "mashed potato mustard oil", "aloo chokha bengali"], true, "katori", kat100(1)],
  ["jadoh", "Jadoh (Khasi pork rice)", "nonveg", 190, 8.0, 22.0, 8.0, "1 plate", 300, ["ja doh", "khasi jadoh", "jadoh rice", "meghalaya rice pork"], true, "plate", plate(0, 300)],
  ["sattu-paratha", "Sattu paratha", "north", 280, 9.0, 38.0, 10.0, "1 paratha", 100, ["sattu ka paratha", "sattu parantha", "bihari sattu paratha", "sattu stuffed paratha", "makuni"], true, "piece", pc(1, 100, "parathas")],
  ["thekua", "Thekua", "sweet", 445, 6.0, 60.0, 20.0, "1 thekua", 30, ["thekwa", "khajuria", "thokwa", "chhath thekua", "thekuaa"], true, "piece", pc(1, 30, "thekuas")],
  ["khaja", "Khaja", "sweet", 465, 5.0, 55.0, 25.0, "1 piece", 30, ["silao khaja", "puri khaja", "odia khaja", "madhu khaja", "khaaja"], true, "piece", pc(0, 30)],
  ["pantua", "Pantua", "sweet", 345, 5.0, 50.0, 14.0, "1 piece", 40, ["ledikeni", "langcha", "lyangcha", "pantoa", "bengali pantua"], true, "piece", pc(1, 40)],
  ["gond-ladoo", "Gond ladoo", "sweet", 490, 9.0, 42.0, 32.0, "1 ladoo", 40, ["gond ke laddu", "gond laddu", "dinkache ladoo", "gondh laddoo", "edible gum ladoo"], true, "piece", pc(1, 40, "ladoos")],

  /* ---------------- Goan ---------------- */
  ["goan-fish-curry", "Goan fish curry", "nonveg", 145, 11.0, 5.0, 9.0, "1 katori", 150, ["xitti kodi", "goan fish curry rice", "fish curry goan", "goan coconut fish curry", "kokum fish curry", "hooman"], true, "katori", kat(1)],
  ["goan-prawn-curry", "Goan prawn curry", "nonveg", 150, 12.0, 5.0, 9.0, "1 katori", 150, ["sungta hooman", "goan prawn curry rice", "prawn coconut curry", "kolambi curry"], true, "katori", kat(1)],
  ["prawn-balchao", "Prawn balchão", "nonveg", 215, 14.0, 8.0, 14.0, "1 katori", 100, ["prawn balchao", "balchao", "balchão", "goan prawn pickle", "prawns balchao"], true, "katori", kat100(1)],
  ["pork-vindaloo", "Pork vindaloo", "nonveg", 240, 15.0, 4.0, 18.0, "1 katori", 150, ["vindaloo", "vindalho", "goan vindaloo", "pork vindalho", "vindalu"], true, "katori", kat(1)],
  ["chicken-vindaloo", "Chicken vindaloo", "nonveg", 180, 15.0, 5.0, 11.0, "1 katori", 150, ["chicken vindalho", "goan chicken vindaloo", "vindaloo chicken"], true, "katori", kat(1)],
  ["chicken-xacuti", "Chicken xacuti", "nonveg", 195, 14.0, 6.0, 13.0, "1 katori", 150, ["xacuti", "shagoti", "sagoti", "chicken shagoti", "xacuti chicken", "mutton xacuti"], true, "katori", kat(1)],
  ["chicken-cafreal", "Chicken cafreal", "nonveg", 180, 20.0, 3.0, 10.0, "1 piece", 150, ["cafreal", "galinha cafreal", "goan green chicken", "chicken cafrael"], true, "piece", x(1, [["Half chicken", 300], ["100 g", 100]])],
  ["sorpotel", "Sorpotel", "nonveg", 235, 14.0, 4.0, 18.0, "1 katori", 150, ["sarapatel", "pork sorpotel", "goan sorpotel", "sorpatel"], true, "katori", kat(0)],
  ["fish-recheado", "Fish recheado", "nonveg", 195, 17.0, 5.0, 12.0, "1 piece", 120, ["recheado", "recheado fish", "mackerel recheado", "pomfret recheado", "recheado masala fish"], true, "piece", pc(1, 120)],
  ["ros-omelette", "Ros omelette", "egg", 160, 8.0, 5.0, 12.0, "1 plate", 250, ["ross omelette", "goan ros omelette", "omelette with gravy", "ros omlet"], true, "plate", plate(0, 250)],
  ["poi-bread", "Poi (Goan bread)", "bread", 255, 9.0, 50.0, 2.0, "1 poi", 70, ["poee", "goan poi", "goan pao", "pao goa", "undo", "poie"], true, "piece", pc(1, 70)],
  ["bebinca", "Bebinca", "sweet", 335, 5.0, 38.0, 18.0, "1 piece", 60, ["bebinka", "bibik", "goan bebinca", "bebik"], true, "piece", pc(1, 60)],

  /* ---------------- Street food & chaat ---------------- */
  ["sev-puri", "Sev puri", "snack", 300, 6.0, 38.0, 14.0, "1 plate (6 puris)", 120, ["sevpuri", "sev poori", "sev batata puri", "sev puri plate", "bombay sev puri"], true, "plate", plate(2, 120)],
  ["dahi-puri", "Dahi puri", "snack", 190, 5.0, 25.0, 8.0, "1 plate (6 puris)", 150, ["dahi poori", "dahi batata puri", "dahi puri plate", "dahi golgappa", "dahi pani puri"], true, "plate", plate(2, 150)],
  ["papdi-chaat", "Papdi chaat", "snack", 230, 5.0, 30.0, 10.0, "1 plate", 180, ["papri chaat", "dahi papdi chaat", "papdi chat", "dahi papdi", "papri chat", "delhi papdi chaat"], true, "plate", plate(2, 180)],
  ["aloo-tikki", "Aloo tikki", "snack", 200, 3.0, 24.0, 10.0, "1 tikki", 60, ["alu tikki", "potato tikki", "aloo patties", "aloo tikkis", "tikki", "potato cutlet"], true, "piece", pc(2, 60, "tikkis")],
  ["aloo-tikki-chaat", "Aloo tikki chaat", "snack", 195, 4.0, 25.0, 9.0, "1 plate (2 tikki)", 200, ["tikki chaat", "alu tikki chaat", "aloo tikki chat", "chole tikki", "tikki chole chaat", "ragda tikki"], true, "plate", plate(2, 200)],
  ["ragda-pattice", "Ragda pattice", "snack", 180, 5.0, 24.0, 7.0, "1 plate", 250, ["ragda patties", "ragda pattis", "ragda petis", "ragda", "pattice ragda", "ragda patis"], true, "plate", plate(2, 250)],
  ["samosa-chaat-plate", "Samosa chaat (with chole)", "snack", 240, 5.0, 28.0, 12.0, "1 plate", 200, ["samosa chole", "samosa chaat plate", "chole samosa", "samosa chat", "samosa ragda", "samose chaat"], true, "plate", plate(2, 200)],
  ["kachori", "Khasta kachori", "snack", 415, 8.0, 42.0, 24.0, "1 kachori", 50, ["khasta kachori", "dal kachori", "kachodi", "kachori sabzi", "kachauri", "khasta kachodi", "moong dal kachori"], true, "piece", pc(2, 50, "kachoris")],
  ["raj-kachori", "Raj kachori", "snack", 250, 6.0, 30.0, 12.0, "1 raj kachori", 200, ["raaj kachori", "raj kachodi", "raj kachori chaat", "rajkachori"], true, "piece", x(1, [["½ raj kachori", 100], ["100 g", 100]])],
  ["chole-kulche", "Chole kulche", "north", 210, 6.5, 30.0, 7.0, "1 plate (2 kulche)", 300, ["chhole kulche", "chole kulcha", "chana kulcha", "kulche chole", "chole kulchay", "delhi chole kulche"], true, "plate", plate(2, 300)],
  ["matar-kulcha", "Matar kulcha", "north", 190, 6.0, 28.0, 6.0, "1 plate (2 kulche)", 300, ["matar kulche", "mattar kulcha", "delhi matar kulcha", "safed matar kulcha"], true, "plate", plate(1, 300)],
  ["dabeli", "Dabeli", "fastfood", 240, 5.0, 35.0, 9.0, "1 dabeli", 120, ["kutchi dabeli", "double roti", "dabeli pav", "kachchhi dabeli", "dabeli bun", "dabelli"], true, "piece", pc(2, 120, "dabelis")],
  ["aloo-chaat", "Aloo chaat", "snack", 170, 3.0, 22.0, 8.0, "1 plate", 150, ["alu chaat", "aloo chat", "fried aloo chaat", "delhi aloo chaat", "potato chaat"], true, "plate", plate(1, 150)],
  ["chana-chaat", "Chana chaat", "snack", 150, 8.0, 20.0, 4.0, "1 plate", 150, ["chana chat", "kabuli chana chaat", "chickpea chaat", "kala chana chaat", "chole chaat"], true, "plate", plate(2, 150)],
  ["egg-roll", "Egg roll (Kolkata kathi)", "egg", 245, 8.0, 28.0, 11.0, "1 roll", 180, ["anda roll", "egg kathi roll", "egg frankie roll", "kolkata egg roll", "double egg roll"], true, "piece", pc(2, 180, "rolls")],
  ["paneer-kathi-roll", "Paneer tikka roll", "fastfood", 250, 9.0, 27.0, 12.0, "1 roll", 200, ["paneer tikka roll", "paneer kathi roll", "paneer tikka kathi roll", "paneer tikka frankie", "paneer wrap"], true, "piece", pc(1, 200, "rolls")],
  ["mutton-kathi-roll", "Mutton kathi roll", "nonveg", 250, 11.0, 25.0, 12.0, "1 roll", 200, ["mutton roll", "mutton kathi kabab roll", "seekh kebab roll", "mutton frankie", "boti roll"], true, "piece", pc(1, 200, "rolls")],
  ["chicken-momos-steamed", "Chicken momos (steamed)", "nonveg", 170, 9.0, 24.0, 4.0, "1 momo", 30, ["chicken momo", "chicken dumplings", "steamed chicken momos", "chicken mo mo", "chicken momos plate"], true, "piece", x(2, [["1 plate (6)", 180], ["1 plate (8)", 240], ["100 g", 100]])],
  ["veg-fried-momos", "Veg fried momos", "fastfood", 250, 5.0, 30.0, 12.0, "1 momo", 30, ["veg fried momo", "fried veg momos", "crispy momos", "fried momo veg"], true, "piece", x(1, [["1 plate (6)", 180], ["1 plate (8)", 240], ["100 g", 100]])],
  ["chicken-fried-momos", "Chicken fried momos", "nonveg", 250, 9.0, 26.0, 12.0, "1 momo", 30, ["fried chicken momos", "chicken fried momo", "crispy chicken momos"], true, "piece", x(1, [["1 plate (6)", 180], ["1 plate (8)", 240], ["100 g", 100]])],
  ["paneer-momos", "Paneer momos (steamed)", "fastfood", 195, 8.0, 25.0, 7.0, "1 momo", 30, ["paneer momo", "paneer dumplings", "steamed paneer momos", "cheese momos"], true, "piece", x(1, [["1 plate (6)", 180], ["1 plate (8)", 240], ["100 g", 100]])],
  ["tandoori-momos", "Tandoori momos", "fastfood", 220, 8.0, 24.0, 10.0, "1 momo", 30, ["tandoori momo", "afghani momos", "tandoori chicken momos", "tandoori veg momos", "malai momos"], true, "piece", x(1, [["1 plate (6)", 180], ["1 plate (8)", 240], ["100 g", 100]])],
  ["litti", "Litti (sattu stuffed, with ghee)", "north", 320, 8.0, 45.0, 12.0, "1 litti", 80, ["litti chokha", "litti chokha plate", "sattu litti", "bihari litti", "littis", "baati chokha"], true, "piece", pc(2, 80, "littis")],
  ["chokha", "Chokha (baingan-aloo)", "north", 100, 2.0, 12.0, 5.0, "1 katori", 100, ["baingan chokha", "aloo chokha", "baigan chokha", "chokha bihari", "alu chokha"], true, "katori", kat100(1)],
  ["bread-pakora", "Bread pakora", "snack", 270, 6.0, 30.0, 14.0, "1 piece", 80, ["bread pakoda", "bread bajji", "stuffed bread pakora", "aloo bread pakora", "bread pakode", "bread bhaji"], true, "piece", pc(2, 80)],
  ["mathri", "Mathri", "snack", 485, 8.0, 52.0, 27.0, "1 mathri", 15, ["mathi", "mathiya", "methi mathri", "namak para", "namak pare", "matthi"], true, "piece", pc(1, 15, "mathris")],
  ["shakkarpara", "Shakarpara", "sweet", 445, 6.0, 60.0, 20.0, "1 handful", 30, ["shakkarpare", "shankarpali", "shakar para", "sweet diamond cuts", "shankarpale"], true, "serving", x(1, [["1 bowl", 60], ["100 g", 100]])],

  /* ---------------- Indo-Chinese ---------------- */
  ["chilli-chicken-dry", "Chilli chicken (dry)", "nonveg", 210, 15.0, 10.0, 12.0, "1 plate", 200, ["chilly chicken", "chilli chicken dry", "chili chicken", "chilli chiken", "chicken chilli dry", "chilly chicken dry"], true, "plate", plate(3, 200)],
  ["chilli-chicken-gravy", "Chilli chicken (gravy)", "nonveg", 150, 11.0, 8.0, 8.0, "1 plate", 250, ["chilli chicken gravy", "chilly chicken gravy", "chicken chilli gravy", "chili chicken gravy"], true, "plate", plate(1, 250)],
  ["chilli-paneer", "Chilli paneer", "fastfood", 220, 11.0, 10.0, 15.0, "1 plate", 200, ["chilly paneer", "chili paneer", "paneer chilli", "chilli paneer dry", "chilli paneer gravy", "paneer chilly"], true, "plate", plate(2, 200)],
  ["chicken-manchurian", "Chicken manchurian", "nonveg", 180, 13.0, 10.0, 10.0, "1 plate", 200, ["chicken manchuria", "chicken manjurian", "chicken manchurian gravy", "chicken manchurian dry"], true, "plate", plate(2, 200)],
  ["veg-manchurian-gravy", "Veg manchurian (gravy)", "fastfood", 125, 2.5, 13.0, 7.0, "1 plate", 250, ["gobi manchurian gravy", "manchurian with gravy", "veg manchurian wet", "veg balls gravy"], true, "plate", plate(1, 250)],
  ["dragon-chicken", "Dragon chicken", "nonveg", 240, 14.0, 14.0, 14.0, "1 plate", 200, ["dragon chiken", "chicken dragon", "dragon chicken dry"], true, "plate", plate(1, 200)],
  ["chicken-lollipop-pc", "Chicken lollipop", "nonveg", 250, 17.0, 10.0, 16.0, "1 lollipop", 40, ["chicken lolipop", "lollipop chicken", "drums of heaven", "chicken lollypop", "chicken lollipops"], true, "piece", x(2, [["1 plate (6)", 240], ["4 lollipops", 160], ["100 g", 100]])],
  ["chilli-fish", "Chilli fish", "nonveg", 190, 14.0, 9.0, 11.0, "1 plate", 200, ["chilly fish", "fish chilli", "chili fish", "chilli fish dry"], true, "plate", plate(1, 200)],
  ["chilli-mushroom", "Chilli mushroom", "fastfood", 145, 3.5, 10.0, 10.0, "1 plate", 200, ["chilly mushroom", "mushroom chilli", "chili mushroom", "mushroom manchurian"], true, "plate", plate(1, 200)],
  ["baby-corn-chilli", "Chilli baby corn", "fastfood", 165, 3.0, 16.0, 10.0, "1 plate", 200, ["baby corn manchurian", "chilli babycorn", "baby corn chilli", "crispy baby corn", "babycorn fry"], true, "plate", plate(1, 200)],
  ["crispy-corn", "Crispy corn", "fastfood", 245, 4.0, 30.0, 12.0, "1 plate", 150, ["crispy fried corn", "salt and pepper corn", "corn crispy", "crispy corn kernels"], true, "plate", plate(1, 150)],
  ["honey-chilli-potato", "Honey chilli potato", "fastfood", 260, 3.0, 35.0, 12.0, "1 plate", 200, ["chilli potato", "honey chilly potato", "honey chili potato", "chilli potato fries", "honey chilli potatoes"], true, "plate", plate(2, 200)],
  ["schezwan-noodles-plate", "Schezwan noodles", "fastfood", 185, 4.0, 26.0, 7.0, "1 plate", 300, ["szechuan noodles", "schezwan hakka noodles", "sezwan noodles", "schezwan chowmein", "chilli garlic noodles"], true, "plate", plate(2, 300)],
  ["schezwan-fried-rice", "Schezwan fried rice", "fastfood", 175, 3.5, 27.0, 6.0, "1 plate", 300, ["szechuan fried rice", "sezwan fried rice", "schezwan rice", "veg schezwan fried rice", "chicken schezwan fried rice", "shezwan fried rice"], true, "plate", plate(2, 300)],
  ["triple-schezwan", "Triple schezwan rice", "fastfood", 190, 5.0, 24.0, 8.0, "1 plate", 400, ["triple schezwan fried rice", "triple szechuan rice", "triple sezwan", "triple rice", "chicken triple schezwan"], true, "plate", plate(1, 400)],
  ["american-chopsuey", "American chopsuey", "fastfood", 210, 4.0, 28.0, 9.0, "1 plate", 300, ["american chop suey", "chopsuey", "chop suey", "veg american chopsuey", "chicken american chopsuey"], true, "plate", plate(1, 300)],
  ["manchow-soup", "Manchow soup (veg)", "veg", 55, 2.0, 7.0, 2.0, "1 bowl", 250, ["veg manchow soup", "manchow", "manchow soup with noodles", "manchaw soup"], true, "bowl", bowl(2, 250)],
  ["chicken-manchow-soup", "Chicken manchow soup", "nonveg", 60, 4.0, 6.0, 2.0, "1 bowl", 250, ["chicken manchow", "manchow chicken soup", "chicken manchaw soup"], true, "bowl", bowl(1, 250)],
  ["hot-sour-soup", "Hot & sour soup (veg)", "veg", 45, 2.0, 6.0, 1.5, "1 bowl", 250, ["hot n sour soup", "hot and sour veg soup", "veg hot sour soup", "hot sour soup", "chicken hot and sour soup"], true, "bowl", bowl(2, 250)],
  ["sweet-corn-soup-veg", "Sweet corn soup (veg)", "veg", 55, 1.5, 10.0, 1.0, "1 bowl", 250, ["veg sweet corn soup", "sweetcorn soup", "corn veg soup", "cream of corn soup"], true, "bowl", bowl(2, 250)],
  ["chicken-sweet-corn-soup", "Chicken sweet corn soup", "nonveg", 60, 4.0, 8.0, 1.5, "1 bowl", 250, ["chicken corn soup", "chicken sweetcorn soup", "sweet corn chicken soup"], true, "bowl", bowl(1, 250)],

  /* ---------------- North-Indian & Bengali sweets ---------------- */
  ["kaju-katli", "Kaju katli", "sweet", 490, 10.5, 56.0, 25.0, "1 piece", 15, ["kaju barfi", "kaju katri", "kaju kathli", "cashew barfi", "kaju katali", "kaju katari"], true, "piece", pc(2, 15)],
  ["soan-papdi", "Soan papdi", "sweet", 490, 6.0, 62.0, 24.0, "1 piece", 25, ["son papdi", "soan papri", "sohan papdi", "patisa", "son papri", "shonpapdi"], true, "piece", pc(2, 25)],
  ["moong-dal-halwa", "Moong dal halwa", "sweet", 410, 7.0, 40.0, 25.0, "1 katori", 80, ["moong ka halwa", "moong halwa", "mung dal halwa", "moong daal halwa"], true, "katori", x(1, [["2 tbsp", 40], ["1 large katori", 120], ["100 g", 100]])],
  ["gajar-halwa", "Gajar ka halwa", "sweet", 250, 5.0, 30.0, 12.0, "1 katori", 100, ["gajar ka halwa", "gajrela", "carrot halwa with khoya", "gajar halwa with mawa", "gajar halva"], true, "katori", x(2, [["½ katori", 50], ["1 large katori", 150], ["100 g", 100]])],
  ["rice-kheer", "Kheer (rice)", "sweet", 140, 4.0, 20.0, 4.5, "1 katori", 150, ["chawal ki kheer", "chawal kheer", "kheer bowl", "payesh", "payesam bengali", "doodh pak", "kheeri"], true, "katori", kat(2)],
  ["makhana-kheer", "Makhana kheer", "sweet", 135, 4.5, 18.0, 5.0, "1 katori", 150, ["makhane ki kheer", "phool makhana kheer", "lotus seed kheer"], true, "katori", kat(1)],
  ["phirni", "Phirni", "sweet", 150, 4.0, 22.0, 5.0, "1 bowl", 100, ["firni", "phirnee", "kesar phirni", "matka phirni", "rice phirni"], true, "bowl", x(1, [["1 matka (125 g)", 125], ["100 g", 100]])],
  ["rabri", "Rabri", "sweet", 270, 8.0, 28.0, 14.0, "1 katori", 80, ["rabdi", "rabadi", "rabri malai", "lachha rabri", "rabdi sweet"], true, "katori", x(1, [["2 tbsp", 40], ["1 large katori", 120], ["100 g", 100]])],
  ["kulfi", "Kulfi", "sweet", 230, 6.0, 25.0, 12.0, "1 kulfi", 60, ["malai kulfi", "matka kulfi", "kesar pista kulfi", "kulfi stick", "mango kulfi", "kulfee"], true, "piece", pc(2, 60, "kulfis")],
  ["kulfi-falooda", "Kulfi falooda", "sweet", 180, 4.5, 25.0, 7.0, "1 plate", 200, ["kulfi faluda", "falooda kulfi", "kulfi with falooda"], true, "plate", plate(1, 200)],
  ["malpua", "Malpua", "sweet", 335, 5.0, 40.0, 17.0, "1 malpua", 50, ["malpoa", "malpura", "rabri malpua", "maalpua", "pua"], true, "piece", pc(1, 50, "malpuas")],
  ["petha", "Agra petha", "sweet", 340, 0.4, 85.0, 0.2, "1 piece", 30, ["petha sweet", "angoori petha", "kesar petha", "paan petha", "ash gourd sweet"], true, "piece", pc(1, 30)],
  ["besan-ladoo", "Besan ladoo", "sweet", 460, 9.0, 50.0, 25.0, "1 ladoo", 35, ["besan ke laddu", "besan laddoo", "besan ladu", "besan na ladva", "besan unde"], true, "piece", pc(2, 35, "ladoos")],
  ["pinni", "Pinni (atta ladoo)", "sweet", 480, 8.0, 45.0, 30.0, "1 pinni", 40, ["atta pinni", "punjabi pinni", "atta ladoo", "gond pinni", "panjiri ladoo", "wheat ladoo"], true, "piece", pc(1, 40, "pinnis")],
  ["kalakand", "Kalakand", "sweet", 345, 13.0, 35.0, 17.0, "1 piece", 35, ["kalakand barfi", "qalaqand", "alwar milk cake", "kalakand sweet", "dharwad kalakand"], true, "piece", pc(1, 35)],
  ["gujiya", "Gujiya", "sweet", 420, 6.0, 50.0, 22.0, "1 gujiya", 45, ["gujia", "karanji", "ghughra", "pedakiya", "mawa gujiya", "gughra", "nevri"], true, "piece", pc(2, 45, "gujiyas")],
  ["balushahi", "Balushahi", "sweet", 435, 4.5, 55.0, 22.0, "1 piece", 45, ["badusha", "balushai", "badushah", "baalushahi", "makhan bada"], true, "piece", pc(1, 45)],
  ["shahi-tukda", "Shahi tukda", "sweet", 340, 6.0, 38.0, 18.0, "1 piece", 80, ["shahi tukra", "double ka meetha", "shahi toast", "bread halwa"], true, "piece", pc(1, 80)],
  ["sheer-khurma", "Sheer khurma", "sweet", 200, 5.0, 25.0, 9.0, "1 katori", 150, ["sheer korma", "sheer khorma", "shir khurma", "sevai sheer khurma", "eid sheer khurma"], true, "katori", kat(1)],
  ["mishti-doi", "Mishti doi", "sweet", 135, 4.0, 20.0, 4.0, "1 cup", 100, ["misti doi", "mishti dahi", "bengali sweet curd", "meetha dahi", "sweet dahi", "mishti doi cup"], true, "cup", x(1, [["1 matka (150 g)", 150], ["100 g", 100]])],
  ["sandesh", "Sandesh", "sweet", 310, 10.0, 45.0, 10.0, "1 piece", 30, ["sondesh", "sandesh sweet", "nolen gur sandesh", "kanchagolla", "kancha golla", "sondesh bengali"], true, "piece", pc(1, 30)],
  ["rasmalai", "Rasmalai", "sweet", 205, 6.5, 26.0, 8.5, "1 piece (with milk)", 70, ["rasmalaai", "ras malaai", "rossomalai", "rasmalai piece", "angoori rasmalai", "rajbhog rasmalai"], true, "piece", pc(2, 70)],
  ["cham-cham", "Cham cham", "sweet", 290, 6.0, 50.0, 7.0, "1 piece", 50, ["chum chum", "chomchom", "chamcham", "malai chum chum", "chum-chum"], true, "piece", pc(1, 50)],
  ["chhena-poda", "Chhena poda", "sweet", 300, 10.0, 38.0, 12.0, "1 piece", 80, ["chenna poda", "chena poda", "chhena pora", "odia chhena poda"], true, "piece", pc(0, 80)],
  ["pitha", "Pitha (patishapta)", "sweet", 270, 5.0, 45.0, 8.0, "1 pitha", 50, ["patishapta", "pithe", "til pitha", "puli pitha", "bhapa pitha", "ghila pitha"], true, "piece", pc(1, 50, "pithas")],

  /* ---------------- North-Indian drinks ---------------- */
  ["salted-lassi", "Salted lassi", "drink", 60, 3.0, 4.5, 3.0, "1 glass", 250, ["namkeen lassi", "salty lassi", "masala lassi", "chaas lassi salted", "namak lassi"], true, "glass", glass(2)],
  ["mango-lassi-glass", "Mango lassi", "drink", 100, 2.8, 16.0, 2.8, "1 glass", 250, ["aam lassi", "mango lassi glass", "mango yogurt drink", "amul mango lassi style"], true, "glass", glass(2)],
  ["malai-lassi", "Malai lassi (Punjabi)", "drink", 135, 3.5, 17.0, 6.0, "1 glass", 300, ["patiala lassi", "punjabi lassi", "malai maar ke lassi", "amritsari lassi", "thick lassi", "kulhad lassi"], true, "glass", glass(1)],
  ["thandai", "Thandai", "drink", 140, 4.0, 17.0, 6.0, "1 glass", 250, ["thandai milk", "holi thandai", "kesar thandai", "sardai", "thandaai"], true, "glass", glass(1)],
  ["kesar-milk", "Kesar milk", "drink", 85, 3.3, 10.0, 3.5, "1 glass", 250, ["kesar doodh", "saffron milk", "kesari milk", "kesar wala doodh", "kesar elaichi milk"], true, "glass", glass(1)],
  ["jaljeera", "Jaljeera", "drink", 30, 0.2, 7.0, 0, "1 glass", 250, ["jal jeera", "jaljira", "jeera pani masala", "jaljeera drink", "zaljeera"], true, "glass", glass(1)],
  ["aam-panna", "Aam panna", "drink", 58, 0.2, 14.0, 0.1, "1 glass", 250, ["aam panha", "kairi panha", "raw mango drink", "kacche aam ka panna", "aam pana", "kairi pani"], true, "glass", glass(1)],
  ["sattu-sharbat", "Sattu sharbat", "drink", 52, 2.5, 9.0, 0.7, "1 glass", 250, ["sattu drink", "sattu ka sharbat", "sattu pani", "namkeen sattu", "chane ka sattu drink"], true, "glass", glass(1)],
  ["kokum-sharbat", "Kokum sharbat", "drink", 48, 0, 12.0, 0, "1 glass", 250, ["kokum juice", "kokum drink", "amsul sharbat", "kokum sherbet"], true, "glass", glass(0)],
  ["bel-sharbat", "Bel sharbat", "drink", 58, 0.6, 14.0, 0.1, "1 glass", 250, ["bael sharbat", "wood apple juice", "bel ka sharbat", "bael juice", "bilva sharbat"], true, "glass", glass(0)],
  ["noon-chai", "Noon chai (Kashmiri pink tea)", "drink", 60, 2.5, 5.0, 3.5, "1 cup", 150, ["noon chai", "pink tea", "kashmiri chai", "sheer chai", "namkeen chai"], true, "cup", cup(0, 150)],
  ["kashmiri-kahwa", "Kashmiri kahwa (with almonds & sugar)", "drink", 40, 0.5, 6.0, 1.5, "1 cup", 150, ["kahwah", "kehwa", "kashmiri kehwa", "saffron kahwa", "qahwa kashmiri"], true, "cup", cup(1, 150)],
  ["mohabbat-ka-sharbat", "Mohabbat ka sharbat", "drink", 75, 1.5, 14.0, 1.5, "1 glass", 250, ["mohabbat sharbat", "rooh afza milk", "rooh afza watermelon milk", "delhi mohabbat ka sharbat", "rose milk watermelon"], true, "glass", glass(1)],
  ["irani-chai", "Irani chai", "drink", 88, 3.0, 10.0, 4.0, "1 cup", 120, ["irani tea", "dum chai", "hyderabadi irani chai", "malai chai", "irani chai cup"], true, "cup", cup(1, 120)],
];
