import type { Row } from "../foods";

/**
 * Restaurant chains & cafés members in Tamil Nadu order from (dine-in, Swiggy, Zomato).
 * Chain items: published India nutrition where the chain publishes it (src "label"), recalled
 * from their menus — kept estimate: true because recipes and portions change. Everything else is a
 * recipe estimate at restaurant oil levels (+20–40% fat vs home). Values per 100 g / 100 ml.
 */

export const rows: Row[] = [
  /* ---------------- McDonald's India (published nutrition, per item) ---------------- */
  ["mcd-mcaloo-tikki", "McDonald's McAloo Tikki burger", "fastfood", 232, 5.8, 34.5, 7.7, "1 burger", 146, ["mcd aloo tikki", "mac aloo tikki", "mcalu tikki", "mcaloo tikki burger", "aloo tikki mcdonalds", "mcdonalds aloo tikki", "mc aloo tikki", "mcaloo burger"], true, "piece", { pop: 2, brand: "McDonald's India", src: "label" }],
  ["mcd-mcveggie", "McDonald's McVeggie burger", "fastfood", 239, 6.1, 29.2, 10.7, "1 burger", 168, ["mcveggie", "mc veggie", "mcd veggie", "mac veggie", "mcveggi", "mcdonalds veg burger", "mcveggie burger"], true, "piece", { pop: 2, brand: "McDonald's India", src: "label" }],
  ["mcd-mcchicken", "McDonald's McChicken burger", "fastfood", 251, 9.8, 26.9, 11.6, "1 burger", 160, ["mc chicken", "mcd chicken burger", "mac chicken", "mcchicken burger", "mcdonalds chicken burger", "mckchicken"], true, "piece", { pop: 2, brand: "McDonald's India", src: "label" }],
  ["mcd-chicken-maharaja-mac", "McDonald's Chicken Maharaja Mac", "fastfood", 233, 11.5, 20.6, 11.5, "1 burger", 296, ["chicken maharaja mac", "maharaja mac", "maharaja mac chicken", "chicken maharaja", "mcd maharaja", "maharaja burger", "big mac india"], true, "piece", { pop: 2, brand: "McDonald's India", src: "label" }],
  ["mcd-veg-maharaja-mac", "McDonald's Veg Maharaja Mac", "fastfood", 272, 6.9, 30.4, 13.4, "1 burger", 306, ["veg maharaja mac", "maharaja mac veg", "veg maharaja", "mcd veg maharaja", "maharaja veg burger"], true, "piece", { pop: 1, brand: "McDonald's India", src: "label" }],
  ["mcd-filet-o-fish", "McDonald's Filet-O-Fish", "fastfood", 250, 11, 28, 10.2, "1 burger", 132, ["filet o fish", "fillet o fish", "filet-o-fish", "mcd fish burger", "fish burger mcdonalds", "filet of fish"], true, "piece", { pop: 1, brand: "McDonald's India", src: "label" }],
  ["mcd-mcspicy-chicken", "McDonald's McSpicy Chicken burger", "fastfood", 242, 11.3, 21.5, 12.4, "1 burger", 186, ["mcspicy chicken", "mc spicy chicken", "mcspicy chicken burger", "spicy chicken mcd", "mcd mcspicy chicken", "mcspicy"], true, "piece", { pop: 2, brand: "McDonald's India", src: "label" }],
  ["mcd-mcspicy-paneer", "McDonald's McSpicy Paneer burger", "fastfood", 328, 10.1, 26.1, 20.1, "1 burger", 199, ["mcspicy paneer", "mc spicy paneer", "mcspicy paneer burger", "paneer burger mcdonalds", "mcd paneer burger"], true, "piece", { pop: 2, brand: "McDonald's India", src: "label" }],
  ["mcd-mcegg", "McDonald's McEgg burger", "fastfood", 234, 10.4, 26.4, 9.6, "1 burger", 125, ["mcegg", "mc egg", "mcd egg burger", "egg burger mcdonalds", "mcegg burger"], true, "piece", { pop: 1, brand: "McDonald's India", src: "label" }],
  ["mcd-chicken-mcgrill", "McDonald's Chicken McGrill", "fastfood", 228, 10.8, 26.9, 8.5, "1 burger", 130, ["mcgrill", "chicken mcgrill", "mc grill", "mcd grill burger"], true, "piece", { pop: 1, brand: "McDonald's India", src: "label" }],
  ["mcd-spicy-paneer-wrap", "McDonald's Big Spicy Paneer Wrap", "fastfood", 270, 8.4, 24.4, 15.2, "1 wrap", 250, ["big spicy paneer wrap", "mcd paneer wrap", "spicy paneer wrap", "mcdonalds paneer wrap", "mcspicy paneer wrap"], true, "piece", { pop: 1, brand: "McDonald's India", src: "label" }],
  ["mcd-fries", "McDonald's French fries", "fastfood", 306, 3.7, 38.9, 14.8, "1 medium fries", 108, ["mcd fries", "mcdonald fries", "mc fries", "mcd medium fries", "mcd large fries", "mcd small fries", "mcfries", "macd fries", "mcdonalds french fries"], true, "serving", { pop: 2, servings: [["1 small fries", 74], ["1 large fries", 154], ["100 g", 100]], brand: "McDonald's India", src: "label" }],
  ["mcd-nuggets", "McDonald's Chicken McNuggets", "fastfood", 281, 14.4, 17.5, 16.9, "1 nugget", 16, ["mcnuggets", "chicken mcnuggets", "mc nuggets", "mcd nuggets", "mcnugget", "mcdonalds nuggets", "6 pc nuggets mcd"], true, "piece", { pop: 2, servings: [["4 pieces", 64], ["6 pieces", 96], ["9 pieces", 144]], brand: "McDonald's India", src: "label" }],
  ["mcd-mcflurry-oreo", "McDonald's McFlurry Oreo", "sweet", 200, 4.2, 30, 6.9, "1 McFlurry", 130, ["mcflurry", "mc flurry", "mcflurry oreo", "oreo mcflurry", "mcd mcflurry", "mcflury", "mcflurry kitkat"], true, "cup", { pop: 2, brand: "McDonald's India", src: "label" }],
  ["mcd-soft-serve", "McDonald's soft serve cone", "sweet", 156, 3.6, 24.4, 4.9, "1 cone", 90, ["mcd soft serve", "mcd cone", "mcdonalds cone", "mcd softy", "soft serve cone", "mcd ice cream cone", "mcd vanilla cone"], true, "piece", { pop: 2, brand: "McDonald's India", src: "label" }],
  ["mcd-mcpuff", "McDonald's Veg McPuff", "fastfood", 290, 4.5, 32, 16, "1 puff", 100, ["mcpuff", "mc puff", "veg mcpuff", "mcd puff", "mcdonalds puff"], true, "piece", { pop: 1, brand: "McDonald's India", src: "label" }],
  ["mcd-coke", "McDonald's Coke (medium)", "drink", 42, 0, 10.5, 0, "1 medium (400 ml)", 400, ["mcd coke", "mcdonalds coke", "mcd soft drink", "mcd coke medium", "mcd pepsi"], true, "glass", { pop: 1, servings: [["1 small (300 ml)", 300], ["1 large (500 ml)", 500]], brand: "McDonald's India", src: "label" }],
  ["mcd-mccafe-cappuccino", "McCafé cappuccino (regular)", "drink", 54, 2.9, 4.6, 2.7, "1 regular (240 ml)", 240, ["mccafe cappuccino", "mcd cappuccino", "mccafe coffee", "mcd coffee"], true, "cup", { pop: 1, servings: [["1 large (350 ml)", 350]], brand: "McDonald's India", src: "label" }],
  ["mcd-mccafe-cold-coffee", "McCafé cold coffee", "drink", 82, 2.3, 12.7, 2.5, "1 regular (300 ml)", 300, ["mccafe cold coffee", "mcd cold coffee", "mcdonalds cold coffee", "mccafe frappe"], true, "glass", { pop: 1, servings: [["1 large (400 ml)", 400]], brand: "McDonald's India", src: "label" }],

  /* ---------------- KFC India ---------------- */
  ["kfc-hot-crispy", "KFC Hot & Crispy chicken (1 piece)", "fastfood", 260, 20, 9, 16, "1 piece", 100, ["kfc hot and crispy", "kfc hot n crispy", "hot and crispy chicken", "kfc chicken piece", "kfc fried chicken", "kfc bucket", "kfc chicken bucket", "hot crispy chicken"], true, "piece", { pop: 2, servings: [["2 pieces", 200], ["4 pieces", 400], ["bucket 8 pieces", 800]], brand: "KFC India", src: "label" }],
  ["kfc-original-recipe", "KFC Original Recipe chicken (1 piece)", "fastfood", 230, 21, 6, 13.5, "1 piece", 100, ["kfc original recipe", "original recipe chicken", "kfc original", "kfc classic chicken", "kfc or chicken"], true, "piece", { pop: 1, servings: [["2 pieces", 200], ["bucket 6 pieces", 600]], brand: "KFC India", src: "label" }],
  ["kfc-smoky-grilled", "KFC Smoky Grilled chicken (1 piece)", "fastfood", 190, 24, 3, 9, "1 piece", 100, ["kfc grilled chicken", "kfc smoky grilled", "smoky grilled chicken", "kfc grill"], true, "piece", { pop: 1, servings: [["2 pieces", 200]], brand: "KFC India", src: "label" }],
  ["kfc-hot-wings", "KFC Hot Wings", "fastfood", 270, 20, 10, 16.7, "1 wing", 30, ["kfc hot wings", "kfc wings", "kfc hot wing", "kfc chicken wings", "kfc wing"], true, "piece", { pop: 2, servings: [["2 wings", 60], ["4 wings", 120], ["6 wings", 180]], brand: "KFC India", src: "label" }],
  ["kfc-popcorn-chicken", "KFC Popcorn chicken (regular)", "fastfood", 307, 17.3, 18.7, 18, "1 regular", 75, ["kfc popcorn", "kfc popcorn chicken", "kfc chicken popcorn", "kfc pop corn"], true, "serving", { pop: 2, servings: [["1 medium", 110], ["1 large", 150], ["100 g", 100]], brand: "KFC India", src: "label" }],
  ["kfc-strips", "KFC Chicken strips", "fastfood", 271, 21.4, 14.3, 14.3, "1 strip", 35, ["kfc strips", "kfc chicken strips", "boneless strips", "kfc strip"], true, "piece", { pop: 1, servings: [["3 strips", 105], ["5 strips", 175]], brand: "KFC India", src: "label" }],
  ["kfc-zinger", "KFC Classic Zinger burger", "fastfood", 237, 11.6, 23.2, 10.8, "1 burger", 190, ["kfc zinger", "classic zinger", "zinger kfc", "kfc zinger burger", "kfc chicken zinger", "zingar burger"], true, "piece", { pop: 2, brand: "KFC India", src: "label" }],
  ["kfc-veg-zinger", "KFC Veg Zinger burger", "fastfood", 233, 5.6, 27.8, 11.1, "1 burger", 180, ["veg zinger", "kfc veg zinger", "kfc veg burger", "veg zinger burger"], true, "piece", { pop: 1, brand: "KFC India", src: "label" }],
  ["kfc-chicken-longer", "KFC Chicken Longer burger", "fastfood", 257, 9.3, 27.1, 12.1, "1 burger", 140, ["chicken longer", "kfc longer", "kfc chicken longer", "longer burger"], true, "piece", { pop: 1, brand: "KFC India", src: "label" }],
  ["kfc-rice-bowlz-chicken", "KFC chicken Rice Bowlz", "fastfood", 156, 6.1, 20.8, 5.3, "1 bowl", 360, ["kfc rice bowl", "rice bowlz", "kfc rice bowlz", "chicken rice bowlz", "kfc chicken rice bowl", "rice bowls kfc"], true, "bowl", { pop: 2, brand: "KFC India", src: "label" }],
  ["kfc-rice-bowlz-veg", "KFC veg Rice Bowlz", "fastfood", 138, 2.9, 21.4, 4.6, "1 bowl", 350, ["veg rice bowlz", "kfc veg rice bowl", "kfc veg rice bowlz", "veg rice bowl kfc"], true, "bowl", { pop: 1, brand: "KFC India", src: "label" }],
  ["kfc-fries", "KFC French fries (medium)", "fastfood", 291, 3.6, 37.3, 14.1, "1 medium fries", 110, ["kfc fries", "kfc french fries", "kfc medium fries", "kfc large fries"], true, "serving", { pop: 2, servings: [["1 regular", 80], ["1 large", 150]], brand: "KFC India", src: "label" }],
  ["kfc-krushers", "KFC Krushers (chocolate)", "drink", 111, 2, 16.7, 4, "1 cup (300 ml)", 300, ["kfc krushers", "krushers", "kfc shake", "kfc chocolate krushers", "kfc cold coffee"], true, "glass", { pop: 1, brand: "KFC India", src: "label" }],

  /* ---------------- Domino's India — pizzas per slice (medium = 6 slices, regular = 4 slices; hand-tossed) ---------------- */
  ["dom-margherita", "Domino's Margherita pizza", "fastfood", 255, 10.5, 33, 9, "1 slice (medium)", 75, ["dominos margherita", "domino margherita", "margherita pizza", "margarita pizza", "dominos margarita", "margherita dominos"], true, "piece", { pop: 2, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-double-cheese-margherita", "Domino's Double Cheese Margherita", "fastfood", 276, 12, 30, 12, "1 slice (medium)", 75, ["double cheese margherita", "dominos double cheese", "double cheese pizza", "double cheese margarita"], true, "piece", { pop: 2, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-farmhouse", "Domino's Farmhouse pizza", "fastfood", 241, 9.5, 31, 8.8, "1 slice (medium)", 75, ["dominos farmhouse", "farmhouse pizza", "farm house pizza", "domino farmhouse", "farmhouse"], true, "piece", { pop: 2, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-peppy-paneer", "Domino's Peppy Paneer pizza", "fastfood", 254, 11, 30, 10, "1 slice (medium)", 75, ["peppy paneer", "dominos peppy paneer", "peppy paneer pizza", "pepy paneer", "peppi paneer"], true, "piece", { pop: 2, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-veg-extravaganza", "Domino's Veg Extravaganza pizza", "fastfood", 246, 10, 30, 9.5, "1 slice (medium)", 75, ["veg extravaganza", "dominos veg extravaganza", "veggie extravaganza", "extravaganza pizza", "veg extravaganza pizza"], true, "piece", { pop: 1, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-mexican-green-wave", "Domino's Mexican Green Wave pizza", "fastfood", 235, 9, 31, 8.3, "1 slice (medium)", 75, ["mexican green wave", "dominos mexican green wave", "mexican pizza dominos", "green wave pizza"], true, "piece", { pop: 1, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-deluxe-veggie", "Domino's Deluxe Veggie pizza", "fastfood", 239, 9.5, 30.5, 8.8, "1 slice (medium)", 75, ["deluxe veggie", "dominos deluxe veggie", "deluxe veggie pizza", "deluxe veg pizza"], true, "piece", { pop: 1, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-cheese-n-corn", "Domino's Cheese n Corn pizza", "fastfood", 251, 10, 33, 8.8, "1 slice (medium)", 75, ["cheese n corn", "cheese and corn pizza", "dominos cheese corn", "corn pizza", "cheese corn pizza"], true, "piece", { pop: 2, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-paneer-makhani", "Domino's Paneer Makhani pizza", "fastfood", 254, 11, 30, 10, "1 slice (medium)", 75, ["paneer makhani pizza", "dominos paneer makhani", "makhani pizza", "paneer makhni pizza"], true, "piece", { pop: 1, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-chicken-dominator", "Domino's Chicken Dominator pizza", "fastfood", 264, 14, 26, 11.5, "1 slice (medium)", 75, ["chicken dominator", "dominos chicken dominator", "chicken dominator pizza", "dominator pizza"], true, "piece", { pop: 2, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-pepper-bbq-chicken", "Domino's Pepper Barbecue Chicken pizza", "fastfood", 251, 12.5, 29, 9.5, "1 slice (medium)", 75, ["pepper barbecue chicken", "pepper bbq chicken", "dominos pepper barbecue", "pepper barbeque chicken pizza", "bbq chicken pizza"], true, "piece", { pop: 2, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-chicken-sausage", "Domino's Chicken Sausage pizza", "fastfood", 259, 12, 29, 10.5, "1 slice (medium)", 75, ["chicken sausage pizza", "dominos chicken sausage", "sausage pizza", "chicken sausage dominos"], true, "piece", { pop: 1, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-chicken-golden-delight", "Domino's Chicken Golden Delight pizza", "fastfood", 254, 12, 29, 10, "1 slice (medium)", 75, ["chicken golden delight", "golden delight pizza", "dominos golden delight", "golden delight"], true, "piece", { pop: 1, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-chicken-fiesta", "Domino's Chicken Fiesta pizza", "fastfood", 251, 12, 29.5, 9.5, "1 slice (medium)", 75, ["chicken fiesta", "dominos chicken fiesta", "fiesta pizza", "chicken fiesta pizza"], true, "piece", { pop: 1, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-non-veg-supreme", "Domino's Non Veg Supreme pizza", "fastfood", 261, 13.5, 27, 11, "1 slice (medium)", 75, ["non veg supreme", "nonveg supreme pizza", "dominos non veg supreme", "non-veg supreme"], true, "piece", { pop: 1, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-keema-do-pyaza", "Domino's Keema Do Pyaza pizza", "fastfood", 259, 13, 28, 10.5, "1 slice (medium)", 75, ["keema do pyaza", "keema pizza", "dominos keema", "keema do pyaaza"], true, "piece", { pop: 1, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["dom-cheese-burst", "Domino's Cheese Burst margherita", "fastfood", 290, 12, 30, 13.5, "1 slice (medium)", 75, ["cheese burst", "cheese burst pizza", "dominos cheese burst", "cheeseburst"], true, "piece", { pop: 2, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],

  /* ---------------- Domino's India — Pizza Mania, sides, desserts ---------------- */
  ["dom-pizza-mania", "Domino's Pizza Mania (onion / tomato)", "fastfood", 230, 8, 34, 6.8, "1 Pizza Mania", 150, ["pizza mania", "dominos pizza mania", "onion pizza mania", "tomato pizza mania", "pizzamania", "corn pizza mania"], true, "piece", { pop: 2, brand: "Domino's India", src: "label" }],
  ["dom-garlic-breadsticks", "Domino's Garlic breadsticks", "fastfood", 339, 8.6, 45, 13.9, "1 breadstick", 28, ["dominos garlic breadsticks", "domino garlic bread sticks", "dominos garlic bread", "garlic breadstick", "dominos breadsticks", "garlic bread dominos"], true, "piece", { pop: 2, servings: [["4 pieces (1 box)", 112], ["2 pieces", 56]], brand: "Domino's India", src: "label" }],
  ["dom-stuffed-garlic-bread", "Domino's Stuffed garlic bread", "fastfood", 300, 10, 36, 13.1, "1 piece", 45, ["dominos stuffed garlic bread", "stuffed garlic breadsticks", "dominos cheesy garlic bread", "domino stuffed garlic bread"], true, "piece", { pop: 2, servings: [["4 pieces (1 box)", 180]], brand: "Domino's India", src: "label" }],
  ["dom-choco-lava-cake", "Domino's Choco Lava Cake", "sweet", 370, 5, 46, 18.5, "1 cake", 100, ["choco lava cake", "chocolava", "choco lava", "dominos lava cake", "lava cake", "chocolate lava cake"], true, "piece", { pop: 2, brand: "Domino's India", src: "label" }],
  ["dom-pasta-white", "Domino's Pasta Italiano (white)", "fastfood", 165, 4.8, 19.1, 7.8, "1 box", 230, ["dominos pasta", "pasta italiano", "dominos white pasta", "dominos pasta white", "creamy tomato pasta dominos"], true, "serving", { pop: 1, brand: "Domino's India", src: "label" }],
  ["dom-taco-mexicana", "Domino's Taco Mexicana (veg)", "fastfood", 203, 5, 23.3, 10, "1 taco", 120, ["taco mexicana", "dominos taco", "taco mexicana veg", "dominos taco mexicana"], true, "piece", { pop: 1, brand: "Domino's India", src: "label" }],
  ["dom-potato-wedges", "Domino's Potato cheese shots / wedges", "fastfood", 182, 2.5, 25, 8, "1 box", 120, ["dominos wedges", "potato wedges dominos", "potato cheese shots", "dominos potato wedges"], true, "serving", { pop: 1, brand: "Domino's India", src: "label" }],

  /* ---------------- Pizza Hut India — pan pizza per slice (medium = 6 slices) ---------------- */
  ["ph-margherita", "Pizza Hut Margherita pan pizza", "fastfood", 270, 11, 31, 11.5, "1 slice (medium pan)", 100, ["pizza hut margherita", "pizzahut margherita", "pan pizza margherita", "pizza hut cheese pizza"], true, "piece", { pop: 2, servings: [["1 personal pan pizza", 260], ["1 medium pizza (6 slices)", 600]], brand: "Pizza Hut India", src: "label" }],
  ["ph-veggie-supreme", "Pizza Hut Veggie Supreme pan pizza", "fastfood", 246, 10, 29, 10, "1 slice (medium pan)", 100, ["veggie supreme", "pizza hut veggie supreme", "veg supreme pizza", "pizzahut veg pizza"], true, "piece", { pop: 1, servings: [["1 personal pan pizza", 260], ["1 medium pizza (6 slices)", 600]], brand: "Pizza Hut India", src: "label" }],
  ["ph-tandoori-paneer", "Pizza Hut Tandoori Paneer pan pizza", "fastfood", 261, 11.5, 29, 11, "1 slice (medium pan)", 100, ["tandoori paneer pizza", "pizza hut tandoori paneer", "pizzahut paneer pizza", "paneer pizza hut"], true, "piece", { pop: 2, servings: [["1 personal pan pizza", 260], ["1 medium pizza (6 slices)", 600]], brand: "Pizza Hut India", src: "label" }],
  ["ph-chicken-supreme", "Pizza Hut Chicken Supreme pan pizza", "fastfood", 255, 13, 27, 10.5, "1 slice (medium pan)", 100, ["chicken supreme", "pizza hut chicken supreme", "chicken supreme pizza", "pizzahut chicken pizza"], true, "piece", { pop: 2, servings: [["1 personal pan pizza", 260], ["1 medium pizza (6 slices)", 600]], brand: "Pizza Hut India", src: "label" }],
  ["ph-chicken-tikka", "Pizza Hut Chicken Tikka pan pizza", "fastfood", 255, 13, 28, 10, "1 slice (medium pan)", 100, ["chicken tikka pizza", "pizza hut chicken tikka", "tikka pizza", "pizzahut tikka"], true, "piece", { pop: 1, servings: [["1 personal pan pizza", 260], ["1 medium pizza (6 slices)", 600]], brand: "Pizza Hut India", src: "label" }],
  ["ph-garlic-bread", "Pizza Hut Garlic bread", "fastfood", 330, 8, 42, 14.5, "1 piece", 40, ["pizza hut garlic bread", "pizzahut garlic bread", "ph garlic bread", "garlic bread pizza hut"], true, "piece", { pop: 1, servings: [["4 pieces", 160]], brand: "Pizza Hut India", src: "label" }],
  ["ph-pasta", "Pizza Hut pasta (white / red)", "fastfood", 170, 5, 19, 8.2, "1 bowl", 250, ["pizza hut pasta", "pizzahut pasta", "ph pasta", "pizza hut white pasta"], true, "bowl", { pop: 1, brand: "Pizza Hut India", src: "label" }],

  /* ---------------- Subway India — 6-inch subs on multigrain, no cheese/sauce (footlong = 2x) ---------------- */
  ["sub-veggie-delite", "Subway Veggie Delite sub (6 inch)", "fastfood", 115, 4.5, 20, 1.8, "1 sub (6 inch)", 200, ["veggie delite", "subway veggie delite", "veggie delight", "subway veg sub", "subway veggie delight"], true, "piece", { pop: 2, servings: [["1 footlong", 400], ["100 g", 100]], brand: "Subway India", src: "label" }],
  ["sub-paneer-tikka", "Subway Paneer Tikka sub (6 inch)", "fastfood", 136, 6.5, 18.3, 4.1, "1 sub (6 inch)", 230, ["subway paneer tikka", "paneer tikka sub", "subway paneer", "paneer tikka sandwich subway"], true, "piece", { pop: 2, servings: [["1 footlong", 460], ["100 g", 100]], brand: "Subway India", src: "label" }],
  ["sub-chicken-tikka", "Subway Chicken Tikka sub (6 inch)", "fastfood", 130, 9.1, 17.4, 2.6, "1 sub (6 inch)", 230, ["subway chicken tikka", "chicken tikka sub", "chicken tikka subway", "subway tikka sub"], true, "piece", { pop: 2, servings: [["1 footlong", 460], ["100 g", 100]], brand: "Subway India", src: "label" }],
  ["sub-roast-chicken", "Subway Roast Chicken sub (6 inch)", "fastfood", 133, 9.5, 18.2, 2.5, "1 sub (6 inch)", 220, ["subway roast chicken", "roast chicken sub", "roasted chicken subway", "subway roasted chicken"], true, "piece", { pop: 2, servings: [["1 footlong", 440], ["100 g", 100]], brand: "Subway India", src: "label" }],
  ["sub-egg-mayo", "Subway Egg Mayo sub (6 inch)", "fastfood", 172, 6.4, 18.2, 8.2, "1 sub (6 inch)", 220, ["subway egg mayo", "egg mayo sub", "egg mayo sandwich", "subway egg sub"], true, "piece", { pop: 2, servings: [["1 footlong", 440], ["100 g", 100]], brand: "Subway India", src: "label" }],
  ["sub-chicken-teriyaki", "Subway Chicken Teriyaki sub (6 inch)", "fastfood", 136, 9.2, 19.2, 2.5, "1 sub (6 inch)", 240, ["subway chicken teriyaki", "chicken teriyaki sub", "teriyaki sub", "subway teriyaki"], true, "piece", { pop: 1, servings: [["1 footlong", 480], ["100 g", 100]], brand: "Subway India", src: "label" }],
  ["sub-aloo-patty", "Subway Aloo Patty sub (6 inch)", "fastfood", 147, 3.9, 23.9, 3.9, "1 sub (6 inch)", 230, ["subway aloo patty", "aloo patty sub", "subway aloo", "aloo patty subway"], true, "piece", { pop: 1, servings: [["1 footlong", 460], ["100 g", 100]], brand: "Subway India", src: "label" }],
  ["sub-corn-peas", "Subway Corn & Peas sub (6 inch)", "fastfood", 135, 4.5, 22.7, 3, "1 sub (6 inch)", 220, ["subway corn and peas", "corn and peas sub", "corn peas subway", "subway corn peas"], true, "piece", { pop: 1, servings: [["1 footlong", 440], ["100 g", 100]], brand: "Subway India", src: "label" }],
  ["sub-tuna", "Subway Tuna sub (6 inch)", "fastfood", 187, 8.3, 17, 9.6, "1 sub (6 inch)", 230, ["subway tuna", "tuna subway sub", "tuna subway", "subway tuna sandwich"], true, "piece", { pop: 1, servings: [["1 footlong", 460], ["100 g", 100]], brand: "Subway India", src: "label" }],
  ["sub-chicken-tikka-salad", "Subway Chicken Tikka salad", "fastfood", 56, 6.7, 4.1, 1.5, "1 salad bowl", 270, ["subway chicken salad", "chicken tikka salad subway", "subway salad chicken", "subway chicken tikka salad"], true, "bowl", { pop: 1, brand: "Subway India", src: "label" }],
  ["sub-paneer-tikka-salad", "Subway Paneer Tikka salad", "fastfood", 73, 5, 4.6, 3.8, "1 salad bowl", 260, ["subway paneer salad", "paneer tikka salad subway", "subway paneer tikka salad", "paneer salad subway"], true, "bowl", { pop: 1, brand: "Subway India", src: "label" }],
  ["sub-veggie-salad", "Subway Veggie Delite salad", "fastfood", 27, 1.3, 4.8, 0.3, "1 salad bowl", 230, ["subway veg salad", "veggie delite salad", "subway veggie salad", "subway salad veg"], true, "bowl", { pop: 1, brand: "Subway India", src: "label" }],
  ["sub-cookie", "Subway cookie (choco chip)", "sweet", 476, 4.4, 64.4, 22.2, "1 cookie", 45, ["subway cookie", "subway cookies", "subway choco chip cookie", "subway chocolate cookie", "subway dark chunk cookie"], true, "piece", { pop: 2, brand: "Subway India", src: "label" }],
  ["sub-sauce", "Subway sauce (mayo / chipotle / sweet onion)", "condiment", 471, 1, 6.2, 49, "1 portion", 21, ["subway sauce", "chipotle southwest", "subway mayo", "subway chipotle", "sweet onion sauce", "subway mint mayo"], true, "piece", { pop: 1, brand: "Subway India", src: "label" }],

  /* ---------------- Burger King India ---------------- */
  ["bk-chicken-whopper", "Burger King Chicken Whopper", "fastfood", 216, 10.4, 18.5, 11.1, "1 burger", 270, ["chicken whopper", "bk whopper", "burger king whopper", "whopper chicken", "bk chicken whopper", "wopper"], true, "piece", { pop: 2, brand: "Burger King India", src: "label" }],
  ["bk-veg-whopper", "Burger King Veg Whopper", "fastfood", 214, 5.4, 23.8, 10.8, "1 burger", 260, ["veg whopper", "bk veg whopper", "whopper veg", "burger king veg whopper"], true, "piece", { pop: 2, brand: "Burger King India", src: "label" }],
  ["bk-crispy-veg", "Burger King Crispy Veg burger", "fastfood", 244, 5.4, 33.1, 10, "1 burger", 130, ["crispy veg", "bk crispy veg", "crispy veg burger", "burger king veg burger", "bk veg burger"], true, "piece", { pop: 2, brand: "Burger King India", src: "label" }],
  ["bk-crispy-chicken", "Burger King Crispy Chicken burger", "fastfood", 249, 9.3, 27.1, 11.4, "1 burger", 140, ["crispy chicken burger", "bk crispy chicken", "bk chicken burger", "burger king chicken burger"], true, "piece", { pop: 2, brand: "Burger King India", src: "label" }],
  ["bk-veg-surprise", "Burger King Veg Surprise", "fastfood", 236, 5, 32.1, 9.6, "1 burger", 140, ["veg surprise", "bk veg surprise", "veg surprise burger", "burger king veg surprise"], true, "piece", { pop: 1, brand: "Burger King India", src: "label" }],
  ["bk-paneer-royale", "Burger King Paneer Royale", "fastfood", 243, 8.7, 21.7, 13.5, "1 burger", 230, ["paneer royale", "bk paneer", "bk paneer burger", "paneer king burger", "burger king paneer"], true, "piece", { pop: 1, brand: "Burger King India", src: "label" }],
  ["bk-fries", "Burger King fries (medium)", "fastfood", 291, 3.6, 37.3, 14.1, "1 medium fries", 110, ["bk fries", "burger king fries", "bk peri peri fries", "king fries"], true, "serving", { pop: 1, servings: [["1 regular", 80], ["1 large", 150]], brand: "Burger King India", src: "label" }],

  /* ---------------- Taco Bell India ---------------- */
  ["tb-crunchy-taco-veg", "Taco Bell veg Crunchy Taco", "fastfood", 224, 5.9, 23.5, 11.8, "1 taco", 85, ["taco bell taco", "crunchy taco", "taco bell veg taco", "veg crunchy taco"], true, "piece", { pop: 1, brand: "Taco Bell India", src: "label" }],
  ["tb-crunchy-taco-chicken", "Taco Bell chicken Crunchy Taco", "fastfood", 220, 10, 18.9, 11.7, "1 taco", 90, ["chicken crunchy taco", "taco bell chicken taco", "taco bell crunchy chicken", "taco bell chicken crunchy"], true, "piece", { pop: 1, brand: "Taco Bell India", src: "label" }],
  ["tb-crunchwrap-veg", "Taco Bell veg Crunchwrap Supreme", "fastfood", 225, 5.7, 28.7, 9.8, "1 crunchwrap", 230, ["crunchwrap", "crunch wrap", "crunchwrap supreme", "taco bell crunchwrap", "veg crunchwrap"], true, "piece", { pop: 2, brand: "Taco Bell India", src: "label" }],
  ["tb-crunchwrap-chicken", "Taco Bell chicken Crunchwrap Supreme", "fastfood", 221, 8.8, 25, 9.6, "1 crunchwrap", 240, ["chicken crunchwrap", "crunchwrap chicken", "taco bell chicken crunchwrap", "chicken crunch wrap"], true, "piece", { pop: 1, brand: "Taco Bell India", src: "label" }],
  ["tb-quesadilla-chicken", "Taco Bell Chicken Quesadilla", "fastfood", 260, 12.8, 22.2, 13.3, "1 quesadilla", 180, ["taco bell quesadilla", "taco bell chicken quesadilla", "tb quesadilla", "taco bell kesadilla"], true, "piece", { pop: 1, brand: "Taco Bell India", src: "label" }],
  ["tb-burrito-veg", "Taco Bell Burrito (veg)", "fastfood", 185, 5, 26.7, 6.5, "1 burrito", 300, ["taco bell burrito", "taco bell veg burrito", "burrito taco bell", "tb burrito"], true, "piece", { pop: 1, brand: "Taco Bell India", src: "label" }],
  ["tb-nachos", "Taco Bell Nachos with cheese", "fastfood", 318, 5, 33.3, 18.3, "1 serving", 120, ["taco bell nachos", "taco bell nachos cheese", "tb nachos", "taco bell cheesy nachos"], true, "serving", { pop: 1, brand: "Taco Bell India", src: "label" }],

  /* ---------------- Wow! Momo ---------------- */
  ["wow-chicken-momo-steamed", "Wow! Momo chicken steamed momo", "fastfood", 188, 10, 22, 6.8, "1 momo", 25, ["wow momo chicken", "wow momo", "wow momos", "wow chicken momo", "wowmomo", "chicken steamed momo"], true, "piece", { pop: 2, servings: [["1 plate (6 pcs)", 150], ["10 pcs", 250]], brand: "Wow! Momo", src: "recipe" }],
  ["wow-veg-momo-steamed", "Wow! Momo veg steamed momo", "fastfood", 168, 4.4, 26, 5.2, "1 momo", 25, ["wow momo veg", "wow veg momo", "veg steamed momo wow", "wow veg momos"], true, "piece", { pop: 1, servings: [["1 plate (6 pcs)", 150], ["10 pcs", 250]], brand: "Wow! Momo", src: "recipe" }],
  ["wow-fried-chicken-momo", "Wow! Momo fried chicken momo", "fastfood", 280, 9.6, 25.2, 15.6, "1 momo", 25, ["wow fried momo", "wow fried chicken momo", "wow momo fried", "wow fried momos"], true, "piece", { pop: 1, servings: [["1 plate (6 pcs)", 150]], brand: "Wow! Momo", src: "recipe" }],
  ["wow-pan-fried-momo", "Wow! Momo pan-fried chicken momo (sauced)", "fastfood", 230, 9, 24, 11, "1 momo", 30, ["pan fried momo", "wow pan fried momo", "schezwan momo", "chilli momo", "pan fried momos"], true, "piece", { pop: 1, servings: [["1 plate (6 pcs)", 180]], brand: "Wow! Momo", src: "recipe" }],
  ["wow-moburg", "Wow! Momo Moburg (chicken momo burger)", "fastfood", 236, 9.5, 26.3, 10.3, "1 burger", 190, ["moburg", "momo burger", "wow momo burger", "wow moburg"], true, "piece", { pop: 1, brand: "Wow! Momo", src: "recipe" }],

  /* ---------------- Faasos wraps ---------------- */
  ["faasos-chicken-tikka-wrap", "Faasos Chicken Tikka wrap", "fastfood", 225, 11.3, 23.9, 9.3, "1 wrap", 230, ["faasos chicken wrap", "faasos chicken tikka", "fasoos wrap", "faasos wrap", "chicken tikka wrap"], true, "piece", { pop: 2, brand: "Faasos", src: "recipe" }],
  ["faasos-paneer-tikka-wrap", "Faasos Paneer Tikka wrap", "fastfood", 243, 8.3, 25.2, 12.2, "1 wrap", 230, ["faasos paneer wrap", "faasos paneer tikka", "paneer tikka wrap", "fasoos paneer wrap"], true, "piece", { pop: 2, brand: "Faasos", src: "recipe" }],
  ["faasos-seekh-kebab-wrap", "Faasos Chicken Seekh Kebab wrap", "fastfood", 245, 10.5, 23.6, 12, "1 wrap", 220, ["faasos seekh wrap", "seekh kebab wrap", "chicken seekh wrap", "faasos kebab wrap"], true, "piece", { pop: 1, brand: "Faasos", src: "recipe" }],
  ["faasos-aloo-tikki-wrap", "Faasos Aloo Tikki wrap", "fastfood", 214, 4.1, 30, 8.6, "1 wrap", 220, ["faasos aloo wrap", "aloo tikki wrap", "faasos veg wrap", "aloo wrap"], true, "piece", { pop: 1, brand: "Faasos", src: "recipe" }],

  /* ---------------- Behrouz Biryani, Box8, EatFit ---------------- */
  ["behrouz-mutton-biryani", "Behrouz Dum Gosht (mutton) biryani", "nonveg", 200, 9, 22, 8.5, "1 regular (serves 1)", 400, ["behrouz biryani", "behrouz mutton biryani", "behrouz gosht biryani", "dum gosht biryani", "behroz biryani"], true, "plate", { pop: 2, servings: [["1 large (serves 2)", 800], ["100 g", 100]], brand: "Behrouz Biryani", src: "recipe" }],
  ["behrouz-chicken-biryani", "Behrouz Lazeez Bhuna Murgh (chicken) biryani", "nonveg", 196, 9.5, 22, 7.8, "1 regular (serves 1)", 400, ["behrouz chicken biryani", "lazeez bhuna murgh", "behrouz murgh biryani", "behroz chicken biryani"], true, "plate", { pop: 2, servings: [["1 large (serves 2)", 800], ["100 g", 100]], brand: "Behrouz Biryani", src: "recipe" }],
  ["behrouz-veg-biryani", "Behrouz veg (subz) biryani", "rice", 181, 4, 26, 6.8, "1 regular (serves 1)", 400, ["behrouz veg biryani", "behrouz subz biryani", "behrouz paneer biryani", "behroz veg biryani"], true, "plate", { pop: 1, servings: [["1 large (serves 2)", 800]], brand: "Behrouz Biryani", src: "recipe" }],
  ["box8-butter-chicken-rice", "Box8 Butter chicken rice bowl", "nonveg", 154, 7, 18, 6, "1 box", 420, ["box8 butter chicken", "box 8 butter chicken", "box8 chicken rice", "box8 meal"], true, "bowl", { pop: 1, brand: "Box8", src: "recipe" }],
  ["box8-paneer-rice", "Box8 Paneer makhani / dal makhani rice bowl", "north", 146, 4.5, 19, 5.8, "1 box", 420, ["box8 paneer", "box8 dal makhani", "box 8 paneer rice", "box8 veg meal"], true, "bowl", { pop: 1, brand: "Box8", src: "recipe" }],
  ["box8-all-in-one-meal", "Box8 All-in-1 meal (veg, rice + roti + curry)", "north", 140, 4, 20, 4.8, "1 meal", 500, ["box8 all in one", "box8 all in 1 meal", "all in one meal box8", "box8 thali"], true, "plate", { pop: 1, brand: "Box8", src: "recipe" }],
  ["eatfit-chicken-bowl", "EatFit grilled chicken protein bowl", "fastfood", 120, 10, 12, 3.5, "1 bowl", 350, ["eatfit chicken bowl", "eat fit chicken", "eatfit protein bowl", "cult eatfit chicken", "eatfit meal"], true, "bowl", { pop: 1, brand: "EatFit", src: "recipe" }],
  ["eatfit-paneer-bowl", "EatFit paneer protein bowl", "fastfood", 135, 7, 13, 6, "1 bowl", 350, ["eatfit paneer bowl", "eat fit paneer", "eatfit veg bowl", "cult eatfit paneer"], true, "bowl", { pop: 1, brand: "EatFit", src: "recipe" }],

  /* ---------------- Starbucks India (tall 354 ml unless noted, regular milk) ---------------- */
  ["sb-latte", "Starbucks Caffè Latte (tall)", "drink", 54, 3.4, 5.1, 2, "1 tall (354 ml)", 354, ["starbucks latte", "caffe latte starbucks", "sbux latte", "starbucks cafe latte", "starbuck latte"], true, "cup", { pop: 2, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["sb-cappuccino", "Starbucks Cappuccino (tall)", "drink", 40, 2.5, 3.7, 1.6, "1 tall (354 ml)", 354, ["starbucks cappuccino", "starbucks capuccino", "sbux cappuccino", "starbuck cappuccino"], true, "cup", { pop: 2, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["sb-americano", "Starbucks Caffè Americano (tall)", "drink", 4, 0.3, 0.7, 0, "1 tall (354 ml)", 354, ["starbucks americano", "caffe americano", "sbux americano", "starbucks black coffee", "iced americano starbucks"], true, "cup", { pop: 1, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["sb-cafe-mocha", "Starbucks Caffè Mocha (tall)", "drink", 81, 2.8, 9.9, 3.4, "1 tall (354 ml)", 354, ["starbucks mocha", "sbux mocha", "starbucks cafe mocha", "starbucks caffe mocha"], true, "cup", { pop: 1, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["sb-caramel-macchiato", "Starbucks Caramel Macchiato (tall)", "drink", 54, 2.3, 7.6, 1.6, "1 tall (354 ml)", 354, ["starbucks caramel macchiato", "sbux caramel macchiato", "starbucks macchiato", "caramel machiato"], true, "cup", { pop: 1, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["sb-java-chip-frappuccino", "Starbucks Java Chip Frappuccino (tall)", "drink", 87, 1.4, 13.3, 3.1, "1 tall (354 ml)", 354, ["java chip frappuccino", "java chip", "starbucks java chip", "java chip frappe", "starbucks frappuccino"], true, "cup", { pop: 2, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["sb-caramel-frappuccino", "Starbucks Caramel Frappuccino (tall)", "drink", 70, 0.8, 11, 2.5, "1 tall (354 ml)", 354, ["caramel frappuccino", "starbucks caramel frappe", "caramel frappe", "starbucks cold coffee"], true, "cup", { pop: 2, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["sb-mocha-frappuccino", "Starbucks Mocha Frappuccino (tall)", "drink", 75, 1.1, 11.6, 2.7, "1 tall (354 ml)", 354, ["mocha frappuccino", "starbucks mocha frappe", "mocha frappe", "starbucks mocha frappuccino"], true, "cup", { pop: 1, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["sb-hot-chocolate", "Starbucks Signature Hot Chocolate (tall)", "drink", 85, 3.1, 10.5, 3.4, "1 tall (354 ml)", 354, ["starbucks hot chocolate", "signature hot chocolate", "starbucks chocolate drink", "starbucks hot choc"], true, "cup", { pop: 1, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["sb-chai-latte", "Starbucks Chai Tea Latte (tall)", "drink", 54, 1.7, 9.3, 1.1, "1 tall (354 ml)", 354, ["chai tea latte", "starbucks chai", "starbucks chai latte", "starbucks tea"], true, "cup", { pop: 1, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["sb-butter-croissant", "Starbucks Butter croissant", "bread", 400, 7.1, 42.9, 22.1, "1 croissant", 70, ["starbucks croissant", "sbux croissant", "croissant starbucks", "croisant", "starbucks butter croissant"], true, "piece", { pop: 1, brand: "Starbucks India", src: "label" }],
  ["sb-blueberry-muffin", "Starbucks Blueberry muffin", "sweet", 366, 5.5, 47.3, 17.3, "1 muffin", 110, ["starbucks muffin", "starbucks blueberry muffin", "sbux blueberry muffin", "starbucks blue berry muffin"], true, "piece", { pop: 1, brand: "Starbucks India", src: "label" }],
  ["sb-chocolate-muffin", "Starbucks Double chocolate muffin", "sweet", 382, 5.8, 46.7, 19.2, "1 muffin", 120, ["starbucks chocolate muffin", "starbucks double chocolate muffin", "starbucks choco muffin", "sbux chocolate muffin"], true, "piece", { pop: 1, brand: "Starbucks India", src: "label" }],
  ["sb-chicken-sandwich", "Starbucks Chicken tikka sandwich", "fastfood", 224, 10.6, 24.7, 9.1, "1 sandwich", 170, ["starbucks chicken sandwich", "starbucks sandwich chicken", "starbucks tikka sandwich", "starbucks chicken tikka sandwich"], true, "piece", { pop: 1, brand: "Starbucks India", src: "label" }],
  ["sb-paneer-sandwich", "Starbucks Paneer tikka sandwich", "fastfood", 234, 8.8, 25.9, 10.6, "1 sandwich", 170, ["starbucks paneer sandwich", "starbucks veg sandwich", "starbucks sandwich paneer", "starbucks paneer tikka sandwich"], true, "piece", { pop: 1, brand: "Starbucks India", src: "label" }],

  /* ---------------- Café Coffee Day, Chai Point, Third Wave, Theobroma ---------------- */
  ["ccd-cappuccino", "CCD Cappuccino (regular)", "drink", 60, 2.8, 6, 2.8, "1 regular (200 ml)", 200, ["ccd cappuccino", "cafe coffee day cappuccino", "ccd coffee", "coffee day cappuccino"], true, "cup", { pop: 2, servings: [["1 large (300 ml)", 300]], brand: "Café Coffee Day", src: "recipe" }],
  ["ccd-latte", "CCD Café Latte (regular)", "drink", 66, 3.3, 6, 3.3, "1 regular (200 ml)", 200, ["ccd latte", "cafe coffee day latte", "ccd cafe latte", "coffee day latte"], true, "cup", { pop: 1, servings: [["1 large (300 ml)", 300]], brand: "Café Coffee Day", src: "recipe" }],
  ["ccd-cafe-frappe", "CCD Café Frappé (cold coffee)", "drink", 97, 2.3, 14, 3.5, "1 glass (300 ml)", 300, ["ccd cold coffee", "cafe frappe", "ccd frappe", "coffee day cold coffee", "ccd cafe frappe"], true, "glass", { pop: 2, brand: "Café Coffee Day", src: "recipe" }],
  ["ccd-devils-own", "CCD Devil's Own (chocolate cold coffee)", "drink", 126, 2.7, 18, 4.8, "1 glass (300 ml)", 300, ["devils own", "devil's own", "ccd devils own", "ccd chocolate cold coffee"], true, "glass", { pop: 1, brand: "Café Coffee Day", src: "recipe" }],
  ["ccd-hot-chocolate", "CCD Hot chocolate", "drink", 110, 3.5, 15, 4, "1 regular (200 ml)", 200, ["ccd hot chocolate", "coffee day hot chocolate", "ccd chocolate", "cafe coffee day hot chocolate"], true, "cup", { pop: 1, brand: "Café Coffee Day", src: "recipe" }],
  ["chaipoint-masala-chai", "Chai Point masala chai", "drink", 60, 2, 9, 1.8, "1 cup (150 ml)", 150, ["chai point chai", "chaipoint", "chai point masala chai", "chai point tea", "chai point ginger chai"], true, "cup", { pop: 1, servings: [["1 flask (500 ml)", 500]], brand: "Chai Point", src: "recipe" }],
  ["chaipoint-bun-maska", "Chai Point bun maska", "bread", 367, 7.8, 48.9, 15.6, "1 bun maska", 90, ["chai point bun maska", "bun maska chai point", "chaipoint bun maska", "chai point bun"], true, "piece", { pop: 1, brand: "Chai Point", src: "recipe" }],
  ["twc-cappuccino", "Third Wave Coffee cappuccino", "drink", 59, 3.1, 4.6, 3.1, "1 regular (240 ml)", 240, ["third wave cappuccino", "twc cappuccino", "third wave coffee", "thirdwave coffee"], true, "cup", { pop: 1, brand: "Third Wave Coffee", src: "recipe" }],
  ["twc-iced-latte", "Third Wave Coffee iced latte", "drink", 45, 2.3, 3.4, 2.4, "1 regular (350 ml)", 350, ["third wave iced latte", "twc iced latte", "third wave cold coffee", "twc cold coffee"], true, "glass", { pop: 1, brand: "Third Wave Coffee", src: "recipe" }],
  ["theobroma-brownie", "Theobroma chocolate brownie", "sweet", 481, 6.3, 55, 26.3, "1 brownie", 80, ["theobroma brownie", "overload brownie", "theobroma overload", "theobroma chocolate brownie", "theo brownie"], true, "piece", { pop: 1, brand: "Theobroma", src: "recipe" }],
  ["theobroma-cake-slice", "Theobroma cake slice (Dutch truffle)", "sweet", 425, 5, 45, 25, "1 slice", 100, ["theobroma cake", "theobroma dutch truffle", "theobroma truffle cake", "theobroma pastry"], true, "piece", { pop: 1, brand: "Theobroma", src: "recipe" }],

  /* ---------------- Baskin Robbins, Naturals (1 scoop) ---------------- */
  ["br-chocolate", "Baskin Robbins chocolate scoop", "sweet", 230, 4, 27.1, 11.7, "1 scoop", 70, ["baskin robbins chocolate", "br chocolate", "baskin chocolate", "baskin robbins scoop", "baskin robins"], true, "piece", { pop: 1, servings: [["2 scoops", 140]], brand: "Baskin Robbins", src: "label" }],
  ["br-vanilla", "Baskin Robbins vanilla scoop", "sweet", 209, 3.6, 24.3, 10.7, "1 scoop", 70, ["baskin robbins vanilla", "br vanilla", "baskin vanilla", "french vanilla baskin"], true, "piece", { pop: 1, servings: [["2 scoops", 140]], brand: "Baskin Robbins", src: "label" }],
  ["br-mississippi-mud", "Baskin Robbins Mississippi Mud scoop", "sweet", 246, 4.3, 30, 12, "1 scoop", 70, ["mississippi mud", "baskin mississippi mud", "br mississippi mud", "missisippi mud"], true, "piece", { pop: 1, servings: [["2 scoops", 140]], brand: "Baskin Robbins", src: "label" }],
  ["br-cotton-candy", "Baskin Robbins Cotton Candy scoop", "sweet", 213, 3.4, 27.1, 10, "1 scoop", 70, ["cotton candy ice cream", "baskin cotton candy", "br cotton candy", "baskin robbins cotton candy"], true, "piece", { pop: 1, servings: [["2 scoops", 140]], brand: "Baskin Robbins", src: "label" }],
  ["br-hot-fudge-sundae", "Baskin Robbins hot fudge sundae", "sweet", 210, 3.5, 27, 9.8, "1 sundae", 200, ["baskin sundae", "baskin hot fudge sundae", "br sundae", "baskin robbins sundae"], true, "cup", { pop: 1, brand: "Baskin Robbins", src: "label" }],
  ["naturals-tender-coconut", "Naturals tender coconut ice cream", "sweet", 187, 2.9, 24, 8.8, "1 scoop", 75, ["naturals tender coconut", "tender coconut ice cream", "naturals ice cream", "natural ice cream", "naturals"], true, "piece", { pop: 2, servings: [["2 scoops", 150], ["1 cup (100 g)", 100]], brand: "Naturals Ice Cream", src: "recipe" }],
  ["naturals-sitaphal", "Naturals sitaphal ice cream", "sweet", 200, 3.3, 26.7, 8.8, "1 scoop", 75, ["naturals sitaphal", "sitaphal ice cream", "custard apple ice cream", "seetha pazham ice cream"], true, "piece", { pop: 1, servings: [["2 scoops", 150]], brand: "Naturals Ice Cream", src: "recipe" }],
  ["naturals-mango", "Naturals mango ice cream", "sweet", 193, 2.9, 26.7, 8.3, "1 scoop", 75, ["naturals mango", "mango ice cream naturals", "alphonso ice cream", "mango ice cream"], true, "piece", { pop: 1, servings: [["2 scoops", 150]], brand: "Naturals Ice Cream", src: "recipe" }],
  ["naturals-roasted-almond", "Naturals roasted almond / chocolate ice cream", "sweet", 221, 4.7, 22.7, 12.4, "1 scoop", 75, ["naturals roasted almond", "naturals chocolate", "roasted almond ice cream", "naturals choco"], true, "piece", { pop: 1, servings: [["2 scoops", 150]], brand: "Naturals Ice Cream", src: "recipe" }],

  /* ---------------- Haldiram's restaurant ---------------- */
  ["haldiram-raj-kachori", "Haldiram's raj kachori", "snack", 180, 5, 22, 8, "1 plate", 250, ["haldiram raj kachori", "haldirams kachori", "haldiram kachori", "haldirams raj kachori"], true, "plate", { pop: 1, brand: "Haldiram's", src: "recipe" }],
  ["haldiram-chole-kulche", "Haldiram's chole kulche", "north", 172, 5.5, 24, 6, "1 plate", 300, ["haldiram chole kulche", "haldiram kulche", "haldirams chole kulcha", "haldiram chole kulcha"], true, "plate", { pop: 1, brand: "Haldiram's", src: "recipe" }],
  ["haldiram-aloo-tikki-chaat", "Haldiram's aloo tikki chaat", "snack", 190, 3.5, 25, 8.5, "1 plate", 200, ["haldiram tikki chaat", "haldiram aloo tikki", "haldirams aloo tikki chaat", "haldiram chaat"], true, "plate", { pop: 1, brand: "Haldiram's", src: "recipe" }],
  ["haldiram-rasmalai", "Haldiram's rasmalai", "sweet", 218, 6, 25, 10.5, "1 piece", 60, ["haldiram rasmalai", "haldirams rasmalai", "haldiram ras malai", "rasmalai haldirams"], true, "piece", { pop: 1, servings: [["2 pieces", 120]], brand: "Haldiram's", src: "recipe" }],

  /* ---------------- Saravana Bhavan / A2B / Sangeetha / Annapoorna — restaurant versions (oilier than home) ---------------- */
  ["hotel-ghee-roast", "Hotel ghee roast dosa (A2B / Saravana Bhavan)", "breakfast", 245, 4, 30, 12, "1 ghee roast", 130, ["a2b ghee roast", "saravana bhavan ghee roast", "hsb ghee roast", "sangeetha ghee roast", "annapoorna ghee roast", "hotel ghee roast", "restaurant ghee roast"], true, "piece", { pop: 2, servings: [["100 g", 100]], brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-masala-dosa", "Hotel masala dosa (A2B / Saravana Bhavan)", "breakfast", 196, 4, 27, 8, "1 masala dosa", 200, ["a2b masala dosa", "saravana bhavan masala dosa", "hsb masala dosa", "sangeetha masala dosa", "hotel masala dosa", "annapoorna masala dosa"], true, "piece", { pop: 2, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-paper-roast", "Hotel paper roast (plain, large)", "breakfast", 230, 4, 30, 10.5, "1 paper roast", 150, ["a2b paper roast", "saravana bhavan paper roast", "paper roast dosa", "paper dosa", "hotel paper roast"], true, "piece", { pop: 1, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-onion-rava-dosa", "Hotel onion rava dosa", "breakfast", 230, 4, 28, 11.3, "1 dosa", 160, ["a2b onion rava", "saravana bhavan onion rava dosa", "hotel onion rava dosa", "onion rava roast", "sangeetha rava dosa"], true, "piece", { pop: 1, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-mini-tiffin", "Mini tiffin (A2B / Saravana Bhavan)", "breakfast", 175, 4.2, 25, 6.5, "1 plate", 450, ["mini tiffin", "a2b mini tiffin", "saravana bhavan mini tiffin", "hsb mini tiffin", "sangeetha mini tiffin", "minitiffin"], true, "plate", { pop: 2, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-idli-vada-plate", "Hotel idli vada plate (2 idli + 1 vada, sambar, chutney)", "breakfast", 130, 4.3, 18, 4.6, "1 plate", 350, ["idli vada", "idli vadai", "a2b idli vada", "saravana bhavan idli vada", "idly vada plate", "hotel idli vada"], true, "plate", { pop: 2, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-sambar-vada", "Hotel sambar vada (vada in sambar)", "snack", 150, 5, 16, 7.2, "1 bowl", 180, ["sambar vadai bowl", "sambar dip vada", "sambhar vada", "a2b sambar vada", "annapoorna sambar vadai", "sambar vade"], true, "bowl", { pop: 2, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-ghee-pongal", "Hotel ghee pongal", "breakfast", 180, 4, 22, 8.5, "1 plate", 250, ["a2b pongal", "saravana bhavan pongal", "hotel pongal", "hsb pongal", "sangeetha pongal"], true, "plate", { pop: 2, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-ghee-podi-idli", "Ghee podi mini idli (14 pcs)", "breakfast", 200, 4.5, 27, 8.2, "1 plate", 200, ["podi idli", "ghee podi idli", "podi mini idli", "14 idli podi", "ghee podi mini idli", "podi idly"], true, "plate", { pop: 2, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-rava-kesari", "Hotel rava kesari (ghee-rich)", "sweet", 340, 3, 48, 15, "1 portion", 100, ["a2b kesari", "saravana bhavan kesari", "hotel kesari", "ghee kesari", "sangeetha kesari"], true, "katori", { pop: 1, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-badam-halwa", "Badam halwa (A2B / sweet stall)", "sweet", 471, 8, 50, 26.5, "1 portion", 80, ["badam halwa", "a2b badam halwa", "almond halwa", "badam alwa", "badam halva"], true, "piece", { pop: 1, servings: [["100 g", 100], ["250 g box", 250]], brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-degree-coffee", "Hotel filter coffee (davara set, sweeter)", "drink", 75, 2.5, 10, 2.8, "1 davara set", 150, ["a2b coffee", "saravana bhavan coffee", "hsb coffee", "sangeetha coffee", "annapoorna coffee", "hotel coffee", "hotel filter coffee"], true, "cup", { pop: 2, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-special-meals", "South Indian special meals (full plate, typical)", "rice", 140, 3.5, 21, 4.6, "1 meals plate", 750, ["special meals", "full meals", "south indian meals", "saapadu", "a2b meals", "saravana bhavan meals", "unlimited meals", "hotel meals", "veg meals"], true, "plate", { pop: 2, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-vathal-kuzhambu", "Hotel vathal kuzhambu", "veg", 120, 2, 10, 8, "1 small cup", 100, ["hotel vathal kuzhambu", "restaurant vatha kuzhambu", "vathakuzhambu", "vatha kulambu", "vathal kulambu"], true, "katori", { pop: 1, servings: [["1 katori", 150]], src: "recipe" }],
  ["hotel-poriyal", "Hotel poriyal (meals side, oilier)", "veg", 111, 2.5, 9, 7.3, "1 small cup", 80, ["hotel poriyal", "meals poriyal", "restaurant poriyal", "meals side poriyal"], true, "katori", { pop: 1, servings: [["1 katori", 150]], src: "recipe" }],

  /* ---------------- Thalappakatti, SS Hyderabad, Anjappar, Buhari, Junior Kuppanna (restaurant portions) ---------------- */
  ["thalappakatti-mutton-biryani", "Thalappakatti mutton biryani", "nonveg", 195, 9, 20, 8.8, "1 plate", 400, ["thalappakatti biriyani", "thalappakatti mutton biryani", "dindigul thalappakatti", "thalapakatti biryani", "thalappakatti", "thalappakatti mutton", "seeraga samba mutton biryani"], true, "plate", { pop: 2, servings: [["100 g", 100], ["1 bucket (serves 3)", 1200]], brand: "Dindigul Thalappakatti", src: "recipe" }],
  ["thalappakatti-chicken-biryani", "Thalappakatti chicken biryani", "nonveg", 186, 8.5, 21, 7.5, "1 plate", 400, ["thalappakatti chicken biryani", "thalapakatti chicken biryani", "dindigul chicken biryani", "seeraga samba chicken biryani"], true, "plate", { pop: 2, servings: [["100 g", 100]], brand: "Dindigul Thalappakatti", src: "recipe" }],
  ["thalappakatti-chicken-65", "Thalappakatti chicken 65", "nonveg", 260, 20, 9, 16, "1 plate", 150, ["thalappakatti chicken 65", "thalappakatti 65", "dindigul chicken 65", "thalapakatti chicken 65"], true, "plate", { pop: 1, servings: [["100 g", 100]], brand: "Dindigul Thalappakatti", src: "recipe" }],
  ["ss-hyderabad-chicken-biryani", "SS Hyderabad chicken biryani", "nonveg", 190, 8.5, 22, 7.5, "1 plate", 450, ["ss hyderabad biryani", "ss biryani", "ss hyderabad chicken biryani", "ss hyderabadi biryani", "ss chicken biryani"], true, "plate", { pop: 2, servings: [["100 g", 100]], brand: "SS Hyderabad Biryani", src: "recipe" }],
  ["ss-hyderabad-mutton-biryani", "SS Hyderabad mutton biryani", "nonveg", 200, 9, 21, 8.8, "1 plate", 450, ["ss mutton biryani", "ss hyderabad mutton biryani", "ss hyderabadi mutton biryani", "ss biryani mutton"], true, "plate", { pop: 1, servings: [["100 g", 100]], brand: "SS Hyderabad Biryani", src: "recipe" }],
  ["anjappar-chicken-chettinad", "Anjappar chicken Chettinad", "nonveg", 200, 15, 5, 13.5, "1 plate", 200, ["anjappar chicken chettinad", "anjappar chicken", "anjappar chettinad chicken", "anjapar chicken"], true, "plate", { pop: 1, servings: [["100 g", 100]], brand: "Anjappar", src: "recipe" }],
  ["anjappar-mutton-chukka", "Anjappar mutton chukka", "nonveg", 260, 20, 4, 18.2, "1 plate", 150, ["anjappar mutton chukka", "anjappar chukka", "chettinad mutton chukka", "chukka varuval", "mutton chukka varuval", "anjappar mutton"], true, "plate", { pop: 1, servings: [["100 g", 100]], brand: "Anjappar", src: "recipe" }],
  ["anjappar-pepper-chicken", "Anjappar pepper chicken", "nonveg", 231, 19, 5, 15, "1 plate", 150, ["anjappar pepper chicken", "chettinad pepper chicken", "milagu kozhi", "pepper chicken dry", "milagu chicken"], true, "plate", { pop: 1, servings: [["100 g", 100]], brand: "Anjappar", src: "recipe" }],
  ["anjappar-chicken-biryani", "Anjappar chicken biryani", "nonveg", 186, 8.5, 21, 7.5, "1 plate", 400, ["anjappar biryani", "anjappar chicken biryani", "anjapar biryani", "anjappar biriyani"], true, "plate", { pop: 1, servings: [["100 g", 100]], brand: "Anjappar", src: "recipe" }],
  ["buhari-chicken-65", "Buhari chicken 65 (original)", "nonveg", 273, 20, 10, 17, "1 plate", 150, ["buhari chicken 65", "buhari 65", "original chicken 65", "buhari hotel chicken 65", "restaurant chicken 65"], true, "plate", { pop: 1, servings: [["100 g", 100]], brand: "Buhari", src: "recipe" }],
  ["kuppanna-chicken-biryani", "Junior Kuppanna seeraga samba chicken biryani", "nonveg", 190, 8.5, 21, 8, "1 plate", 400, ["junior kuppanna biryani", "kuppanna biryani", "junior kuppanna chicken biryani", "kuppanna chicken biryani"], true, "plate", { pop: 1, servings: [["100 g", 100]], brand: "Junior Kuppanna", src: "recipe" }],
  ["kuppanna-pallipalayam-chicken", "Junior Kuppanna pallipalayam chicken", "nonveg", 223, 18, 4, 15, "1 plate", 150, ["pallipalayam chicken", "palli palayam chicken", "kuppanna pallipalayam", "pallipalayam kozhi"], true, "plate", { pop: 1, servings: [["100 g", 100]], brand: "Junior Kuppanna", src: "recipe" }],
  ["kuppanna-mutton-chops", "Junior Kuppanna mutton chops / varuval", "nonveg", 241, 18, 4, 17, "1 plate", 150, ["kuppanna mutton", "junior kuppanna mutton", "mutton chops", "kuppanna mutton varuval", "kongu mutton varuval"], true, "plate", { pop: 1, servings: [["100 g", 100]], brand: "Junior Kuppanna", src: "recipe" }],

  /* ---------------- Barbeque Nation starters (estimates) ---------------- */
  ["bbqn-grilled-chicken", "Barbeque Nation grilled chicken (skewer)", "nonveg", 210, 22, 4, 11.8, "1 skewer", 60, ["barbeque nation chicken", "bbq nation chicken", "bbq chicken skewer", "chicken skewer", "bbqn chicken"], true, "piece", { pop: 1, servings: [["3 skewers", 180], ["100 g", 100]], brand: "Barbeque Nation", src: "recipe" }],
  ["bbqn-fish-tikka", "Barbeque Nation fish tikka", "nonveg", 180, 19, 3, 10, "1 piece", 30, ["bbq nation fish", "barbeque nation fish", "bbq fish tikka", "bbqn fish"], true, "piece", { pop: 1, servings: [["4 pieces", 120]], brand: "Barbeque Nation", src: "recipe" }],
  ["bbqn-prawns", "Barbeque Nation grilled prawns", "nonveg", 193, 18, 5.3, 11.3, "1 prawn", 15, ["bbq nation prawns", "barbeque nation prawns", "bbq prawns", "grilled prawns"], true, "piece", { pop: 1, servings: [["5 prawns", 75]], brand: "Barbeque Nation", src: "recipe" }],
  ["bbqn-mutton-seekh", "Barbeque Nation mutton seekh kebab", "nonveg", 250, 17, 5, 18, "1 piece", 40, ["bbq nation seekh", "bbqn seekh kebab", "barbeque nation seekh kebab", "bbq mutton kebab"], true, "piece", { pop: 1, servings: [["3 pieces", 120]], brand: "Barbeque Nation", src: "recipe" }],
  ["bbqn-crispy-corn", "Barbeque Nation crispy corn", "snack", 282, 5, 35, 13.5, "1 small bowl", 100, ["bbq nation crispy corn", "bbqn crispy corn", "barbeque nation corn", "bbq crispy corn"], true, "bowl", { pop: 1, brand: "Barbeque Nation", src: "recipe" }],
  ["bbqn-cajun-potato", "Barbeque Nation Cajun spiced potato", "snack", 220, 2.5, 22, 13.5, "1 small bowl", 100, ["cajun potato", "cajun spice potato", "bbq nation potato", "cajun potatoes"], true, "bowl", { pop: 1, brand: "Barbeque Nation", src: "recipe" }],
  ["bbqn-grilled-pineapple", "Barbeque Nation grilled pineapple", "fruit", 112, 0.5, 22, 2.5, "1 piece", 40, ["grilled pineapple", "bbq pineapple", "bbq nation pineapple", "pineapple grill"], true, "piece", { pop: 1, servings: [["3 pieces", 120]], brand: "Barbeque Nation", src: "recipe" }],

  /* ---------------- Iyengar / local bakery ---------------- */
  ["bakery-chicken-puff", "Bakery chicken puff", "snack", 320, 9, 28, 19, "1 puff", 90, ["chicken puffs", "kozhi puff", "bakery chicken puff", "iyengar chicken puff", "chiken puff"], true, "piece", { pop: 2, src: "recipe" }],
  ["bakery-paneer-puff", "Bakery paneer puff", "snack", 319, 8, 30, 18.6, "1 puff", 90, ["paneer puff", "paneer puffs", "bakery paneer puff", "panner puff"], true, "piece", { pop: 1, src: "recipe" }],
  ["bakery-dil-pasand", "Dil pasand (bakery, tutti frutti coconut)", "sweet", 382, 6, 50, 17.5, "1 piece", 100, ["dil pasand", "dil pasand bun", "dilkhush bakery", "dil pasand sweet bun", "dilpasandh"], true, "piece", { pop: 1, src: "recipe" }],
  ["bakery-cream-bun", "Bakery cream bun", "sweet", 340, 6.6, 50, 12.6, "1 bun", 70, ["cream bun bakery", "cream buns", "butter cream bun", "iyengar cream bun", "creambun"], true, "piece", { pop: 2, src: "recipe" }],
  ["bakery-coconut-bun", "Bakery coconut bun", "sweet", 350, 6, 52, 13, "1 bun", 70, ["thengai bun", "iyengar coconut bun", "coconut buns", "sweet coconut bun"], true, "piece", { pop: 1, src: "recipe" }],
  ["bakery-masala-bun", "Masala bun / khara bun (bakery)", "snack", 300, 7, 46, 9.6, "1 bun", 70, ["khara bun", "masala bun", "kara bun", "veg bun", "spicy bun"], true, "piece", { pop: 1, src: "recipe" }],
  ["bakery-veg-sandwich", "Bakery veg mayo sandwich (toasted)", "fastfood", 229, 5.5, 28, 10.5, "1 sandwich", 150, ["bakery sandwich", "mayo sandwich", "veg mayo sandwich", "iyengar bakery sandwich", "bakery veg sandwich"], true, "piece", { pop: 1, src: "recipe" }],
  ["bakery-chicken-roll", "Bakery chicken roll", "snack", 300, 10, 30, 15.5, "1 roll", 100, ["bakery chicken roll", "chicken bread roll", "iyengar chicken roll", "chicken roll bakery"], true, "piece", { pop: 1, src: "recipe" }],
  ["bakery-plum-cake", "Plum cake slice (bakery)", "sweet", 364, 5, 52, 15, "1 slice", 50, ["plum cake slice", "bakery plum cake slice", "iyengar plum cake", "plum cake bakery", "rich plum cake"], true, "piece", { pop: 1, servings: [["250 g cake", 250]], src: "recipe" }],
  ["bakery-butter-biscuit", "Iyengar bakery butter biscuit", "snack", 500, 6, 62, 25, "1 biscuit", 10, ["butter biscuit", "bakery biscuit", "iyengar biscuit", "bakery butter biscuit", "iyengar butter biscuit"], true, "piece", { pop: 2, servings: [["5 biscuits", 50], ["100 g", 100]], src: "recipe" }],

  /* ---------------- Juice shops (Juice World / local) — fresh juice with sugar unless noted, 1 glass 300 ml ---------------- */
  ["juice-watermelon", "Watermelon juice, fresh (juice shop)", "drink", 42, 0.5, 9.8, 0.1, "1 glass (300 ml)", 300, ["tharpoosani juice", "tarbooz juice", "watermelon juice shop", "water melon juice", "watermelon juce"], true, "glass", { pop: 2, servings: [["1 small glass (200 ml)", 200], ["1 large (400 ml)", 400]], src: "recipe" }],
  ["juice-mosambi", "Mosambi juice, fresh (sweet lime)", "drink", 51, 0.5, 12, 0.1, "1 glass (300 ml)", 300, ["mosambi juice shop", "sathukudi juice", "musambi juice", "sweet lime juice shop", "mosumbi juice", "sathukkudi juice"], true, "glass", { pop: 2, servings: [["1 small glass (200 ml)", 200], ["1 large (400 ml)", 400]], src: "recipe" }],
  ["juice-pineapple", "Pineapple juice, fresh (juice shop)", "drink", 56, 0.4, 13.4, 0.1, "1 glass (300 ml)", 300, ["pineapple juice shop", "annasi juice", "pinapple juice", "pine apple juice"], true, "glass", { pop: 1, servings: [["1 small glass (200 ml)", 200], ["1 large (400 ml)", 400]], src: "recipe" }],
  ["juice-grape", "Grape juice, fresh (juice shop)", "drink", 66, 0.4, 15.8, 0.1, "1 glass (300 ml)", 300, ["grape juice shop", "black grape juice", "grapes juice", "thiratchai juice", "kala khatta"], true, "glass", { pop: 1, servings: [["1 small glass (200 ml)", 200], ["1 large (400 ml)", 400]], src: "recipe" }],
  ["juice-pomegranate", "Pomegranate juice, fresh (juice shop)", "drink", 61, 0.3, 14.6, 0.2, "1 glass (300 ml)", 300, ["pomegranate juice shop", "mathulai juice", "anar juice", "pomegranite juice"], true, "glass", { pop: 1, servings: [["1 small glass (200 ml)", 200], ["1 large (400 ml)", 400]], src: "recipe" }],
  ["juice-carrot", "Carrot juice (juice shop)", "drink", 41, 0.8, 9, 0.2, "1 glass (300 ml)", 300, ["carrot juice", "gajar juice", "carrot juice shop", "carot juice"], true, "glass", { pop: 1, servings: [["1 small glass (200 ml)", 200], ["1 large (400 ml)", 400]], src: "recipe" }],
  ["juice-orange", "Orange juice, fresh (juice shop)", "drink", 50, 0.6, 11.8, 0.1, "1 glass (300 ml)", 300, ["fresh orange juice", "orange juice shop", "kamala juice", "narangi juice"], true, "glass", { pop: 1, servings: [["1 small glass (200 ml)", 200], ["1 large (400 ml)", 400]], src: "recipe" }],
  ["juice-muskmelon", "Muskmelon juice (juice shop)", "drink", 46, 0.6, 10.6, 0.1, "1 glass (300 ml)", 300, ["muskmelon juice", "kirni juice", "kharbuja juice", "musk melon juice shop", "mulampazham juice"], true, "glass", { pop: 1, servings: [["1 small glass (200 ml)", 200], ["1 large (400 ml)", 400]], src: "recipe" }],
  ["juice-lemon-soda", "Sweet lime soda / lemon soda", "drink", 40, 0, 10, 0, "1 glass (300 ml)", 300, ["lemon soda shop", "lime soda sweet", "sweet lemon soda", "fresh lime soda", "nimbu soda", "goli soda", "panneer soda"], true, "glass", { pop: 2, servings: [["1 small glass (200 ml)", 200], ["1 large (400 ml)", 400]], src: "recipe" }],
  ["juice-rose-milk", "Rose milk, chilled (juice shop)", "drink", 96, 3, 14.5, 2.9, "1 glass", 250, ["rosemilk", "rose milk shop", "rose paal", "rose flavoured milk", "chilled rose milk"], true, "glass", { pop: 2, servings: [["1 large (350 ml)", 350]], src: "recipe" }],
  ["juice-jigarthanda", "Jigarthanda, juice-shop glass", "drink", 149, 3.6, 22, 5.2, "1 glass", 300, ["jigarthanda madurai", "jigardhanda", "jigarthanda glass", "jigir thanda", "jigarthanda special", "jigar thanda"], true, "glass", { pop: 2, servings: [["1 small (200 ml)", 200]], src: "recipe" }],
  ["juice-mango-milkshake", "Mango milkshake (juice shop)", "drink", 115, 3, 18, 3.4, "1 glass", 300, ["mango milkshake", "mango milk shake", "maambazham milkshake", "alphonso milkshake"], true, "glass", { pop: 2, src: "recipe" }],
  ["juice-chikoo-shake", "Chikoo (sapota) milkshake", "drink", 120, 3, 19.5, 3.3, "1 glass", 300, ["chikoo shake", "sapota shake", "chikoo milkshake", "sapota milkshake", "chiku shake"], true, "glass", { pop: 1, src: "recipe" }],
  ["juice-avocado-shake", "Butter fruit (avocado) milkshake", "drink", 125, 2.8, 15, 6, "1 glass", 300, ["butter fruit shake", "butterfruit milkshake", "avocado milkshake", "avocado shake", "butter fruit juice"], true, "glass", { pop: 2, src: "recipe" }],
  ["juice-dates-shake", "Dates milkshake", "drink", 135, 3.4, 22, 3.6, "1 glass", 300, ["dates shake", "dates milkshake", "pericham pazham shake", "khajur shake", "dates milk shake"], true, "glass", { pop: 1, src: "recipe" }],
  ["juice-thick-shake", "Thick shake (Oreo / KitKat / chocolate)", "drink", 175, 3.8, 25, 6.6, "1 glass (400 ml)", 400, ["thick shake", "juice shop thick shake", "kitkat thick shake shop", "chocolate thick shake", "kitkat thick shake", "thickshake"], true, "glass", { pop: 2, servings: [["1 small (300 ml)", 300]], src: "recipe" }],

  /* ---------------- Shawarma & grill shops ---------------- */
  ["shawarma-roll-special", "Chicken shawarma roll (special / extra mayo, rumali)", "fastfood", 240, 12, 20, 12.4, "1 roll", 280, ["special shawarma", "rumali shawarma", "shawarma special", "mexican shawarma", "shawarma extra mayo", "paratha shawarma"], true, "piece", { pop: 2, src: "recipe" }],
  ["grill-chicken-quarter", "Grill chicken (quarter)", "nonveg", 217, 22.5, 3.5, 12.5, "1 quarter", 180, ["grill chicken", "grilled chicken quarter", "grill chicken quarter", "grill chicken half", "grill chicken full", "griled chicken", "peri peri grill chicken"], true, "plate", { pop: 2, servings: [["1 half", 360], ["1 full", 720], ["100 g", 100]], src: "recipe" }],

  /* ---------------- More chain & hotel favourites ---------------- */
  ["mcd-mcspicy-fried-chicken", "McDonald's McSpicy fried chicken (1 piece)", "fastfood", 272, 20, 9.1, 17.3, "1 piece", 110, ["mcd fried chicken", "mcspicy fried chicken", "mcdonalds fried chicken", "mcd chicken piece"], true, "piece", { pop: 1, servings: [["2 pieces", 220], ["4 pieces", 440]], brand: "McDonald's India", src: "label" }],
  ["kfc-biryani-bucket", "KFC Chicken biryani bucket", "fastfood", 157, 7.1, 19.7, 5.5, "1 bucket", 380, ["kfc biryani", "kfc biryani bucket", "kfc chicken biryani", "biryani bucket kfc"], true, "bowl", { pop: 1, brand: "KFC India", src: "label" }],
  ["dom-burger-pizza", "Domino's Burger Pizza", "fastfood", 239, 8.7, 30, 9.3, "1 burger pizza", 150, ["burger pizza", "dominos burger pizza", "domino burger pizza", "pizza burger dominos"], true, "piece", { pop: 1, brand: "Domino's India", src: "label" }],
  ["dom-indi-chicken-tikka", "Domino's Indi Chicken Tikka pizza", "fastfood", 255, 13, 28, 10, "1 slice (medium)", 75, ["indi chicken tikka", "dominos chicken tikka", "dominos indi tikka", "chicken tikka pizza dominos"], true, "piece", { pop: 1, servings: [["1 slice (regular)", 60], ["1 regular pizza (4 slices)", 240], ["1 medium pizza (6 slices)", 450]], brand: "Domino's India", src: "label" }],
  ["sub-chicken-slice", "Subway Chicken Slice sub (6 inch)", "fastfood", 132, 8.2, 18.6, 2.7, "1 sub (6 inch)", 220, ["subway chicken slice", "chicken slice sub", "subway chicken slices", "chicken slice subway"], true, "piece", { pop: 1, servings: [["1 footlong", 440], ["100 g", 100]], brand: "Subway India", src: "label" }],
  ["sb-iced-latte", "Starbucks Iced Caffè Latte (tall)", "drink", 35, 2.3, 3.4, 1.4, "1 tall (354 ml)", 354, ["starbucks iced latte", "iced caffe latte", "sbux iced latte", "starbucks cold latte"], true, "cup", { pop: 1, servings: [["1 short (236 ml)", 236], ["1 grande (473 ml)", 473], ["1 venti (591 ml)", 591]], brand: "Starbucks India", src: "label" }],
  ["hotel-chapati-kurma", "Hotel chapati kurma (2 chapati + veg kurma)", "north", 190, 4.8, 24.8, 8, "1 plate", 250, ["hotel chapati kurma", "chapathi kurma", "chappathi kurma", "hotel chapati", "a2b chapati", "saravana bhavan chapathi"], true, "plate", { pop: 2, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-poori-masala-plate", "Hotel poori masala (2 poori + potato masala)", "breakfast", 178, 3.3, 22.6, 8.3, "1 plate", 230, ["hotel poori", "a2b poori", "saravana bhavan poori", "poori set", "poori plate", "sangeetha poori"], true, "plate", { pop: 2, brand: "Saravana Bhavan / A2B / Sangeetha", src: "recipe" }],
  ["hotel-parotta-salna", "Parotta with salna (2 parotta + salna)", "bread", 224, 4.8, 26.7, 10.9, "1 plate", 330, ["parotta salna", "porotta salna", "barotta salna", "parotta with salna", "2 parotta salna", "parotta kurma"], true, "plate", { pop: 2, src: "recipe" }],
  ["juice-nungu-sarbath", "Nungu (palm fruit) sarbath", "drink", 60, 0.4, 14.5, 0.1, "1 glass", 250, ["nungu sarbath", "nungu juice", "palm fruit sarbath", "ice apple juice", "nongu sarbath", "taati munjalu juice"], true, "glass", { pop: 1, src: "recipe" }],

];
