/**
 * Turns a food's display name into a brand-free visual description for
 * image prompts: "McDonald's McAloo Tikki burger" → "aloo tikki burger".
 * Image models paint logos when they see brand names, so every brand,
 * chain and trademarked product name is removed or translated here.
 */

const BRANDS = [
  "McDonald's", "McCafé", "KFC", "Domino's", "Pizza Hut", "Subway", "Burger King", "Taco Bell", "Wow! Momo", "Faasos",
  "Behrouz", "Box8", "EatFit", "Starbucks", "CCD", "Chai Point", "Third Wave Coffee", "Theobroma", "Baskin Robbins",
  "Naturals", "Haldiram's", "Minute Khana", "Saravana Bhavan", "A2B", "Sangeetha", "Thalappakatti", "SS Hyderabad",
  "Anjappar", "Buhari", "Junior Kuppanna", "Barbeque Nation", "Britannia", "Parle", "Sunfeast", "Unibic", "McVitie's",
  "Modern", "Harvest Gold", "Elite", "Winkies", "Lay's", "Kurkure", "Bingo", "Uncle Chipps", "Balaji", "Too Yumm",
  "Pringles", "Doritos", "Cornitos", "Crax", "Act II", "Maggi", "Top Ramen", "Ching's", "Knorr", "MTR", "Saffola",
  "Quaker", "Bagrry's", "Kellogg's", "True Elements", "Yoga Bar", "Amul", "Aavin", "Arokya", "Heritage", "Nandini",
  "Mother Dairy", "Hershey's", "Hatsun", "Milky Mist", "Epigamia", "Cadbury", "Nestlé", "Kissan", "Veeba",
  "Dr. Oetker FunFoods", "Pintola", "MyFitness", "Sundrop", "Dabur", "Real Fruit Power", "Real Activ", "Tropicana",
  "B Natural", "Paper Boat", "Bisleri", "Nescafé", "Bru", "Horlicks", "Complan", "Protinex", "Abbott", "MuscleBlaze",
  "Optimum Nutrition", "MyProtein", "Avvatar", "AS-IT-IS", "Nakpro", "RiteBite", "The Whole Truth", "SuperYou",
  "Phab", "Nutrela", "McCain", "Sumeru", "Godrej Yummiez", "ITC Master Chef", "Venky's", "Arun", "Kwality Wall's",
  "Kali Mark", "Mars", "Ferrero", "Perfetti", "Glucon-D",
];

/** [pattern, replacement] — trademarked product names → what the food looks like */
const TM = [
  // everyday (non-branded) names that still carry a brand word
  [/^boost \/ horlicks milk$/i, "malted chocolate health drink with milk"],
  [/^mango juice \/ maaza$/i, "thick mango drink"],
  [/^maggi$/i, "masala instant noodles, cooked"],
  [/^oreo milkshake$/i, "cookies-and-cream milkshake with crushed chocolate cookie on top"],
  [/thick shake \(oreo \/ kitkat \/ chocolate\)/i, "thick chocolate shake topped with crushed chocolate cookies"],
  [/, mtr-style/i, " (restaurant-style)"],
  // biscuits & bakery
  [/parle-g glucose biscuit/i, "rectangular golden glucose biscuits"],
  [/good day cashew cookies/i, "round butter cookies studded with cashew pieces"],
  [/good day butter cookies/i, "round golden butter cookies"],
  [/good day choco chip cookies/i, "round chocolate-chip cookies"],
  [/marie gold|marie light/i, "Marie"],
  [/nutrichoice digestive/i, "wholewheat digestive"],
  [/nutrichoice oats cookies/i, "oat cookies"],
  [/bourbon chocolate cream biscuit/i, "rectangular chocolate biscuits sandwiched with chocolate cream, sugar-sprinkled"],
  [/50-50 sweet & salty biscuit|krackjack sweet & salty/i, "square sweet-and-salty crackers dusted with sugar crystals"],
  [/tiger glucose biscuit/i, "small glucose biscuits"],
  [/milk bikis/i, "round milk biscuits"],
  [/little hearts/i, "small heart-shaped sugar-glazed puff pastry biscuits"],
  [/treat jim jam cream biscuit/i, "round biscuits sandwiched with cream and a red jam centre"],
  [/treat croissant/i, "small packaged croissant"],
  [/nice time coconut biscuit/i, "rectangular coconut biscuits sprinkled with sugar"],
  [/pure magic chocolush cookies/i, "chocolate cookies with a molten chocolate centre"],
  [/toastea premium bake rusk|rusk \(elaichi\)/i, "golden crisp tea rusks"],
  [/monaco salted crackers/i, "round salted crackers"],
  [/hide & seek fab cream biscuit/i, "chocolate-cream sandwich biscuits"],
  [/hide & seek choco chip cookies/i, "dark chocolate-chip cookies"],
  [/happy happy choco chip cakes/i, "small soft chocolate-chip cakes"],
  [/20-20 butter cookies/i, "round butter cookies"],
  [/milano choco chip cookies/i, "chunky chocolate-chip cookies"],
  [/dark fantasy choco fills/i, "round cookies with a soft chocolate filling, one broken open"],
  [/mom's magic cashew & almond cookies/i, "butter cookies with cashew and almond pieces"],
  [/farmlite oats & almonds digestive/i, "oat-and-almond digestive biscuits"],
  [/bounce cream biscuit/i, "cream sandwich biscuits"],
  [/oreo original cream biscuit/i, "round dark chocolate sandwich biscuits with a white cream filling, plain unembossed surface"],
  [/mcvitie's digestive biscuit/i, "wholewheat digestive biscuits"],
  [/winkies fruit cake slice/i, "fruit cake slice"],
  // chips & namkeen
  [/india's magic masala/i, "masala-dusted potato chips"],
  [/american style cream & onion/i, "cream-and-onion potato chips"],
  [/spanish tomato tango/i, "tomato-seasoned potato chips"],
  [/classic salted chips/i, "salted potato chips"],
  [/masala munch/i, "orange masala corn puffs (crinkly sticks)"],
  [/chilli chatka/i, "red chilli corn puffs (crinkly sticks)"],
  [/mad angles achaari masti/i, "triangular achaari-masala corn chips"],
  [/tedhe medhe masala tadka/i, "twisted masala corn sticks"],
  [/spicy treat/i, "spicy potato chips"],
  [/simply salted wafers/i, "thin salted potato wafers"],
  [/pringles original/i, "stacked saddle-shaped salted potato crisps"],
  [/pringles sour cream & onion/i, "stacked saddle-shaped sour-cream-and-onion potato crisps"],
  [/doritos nacho cheese/i, "cheese-dusted triangular tortilla chips"],
  [/crax corn rings/i, "crunchy corn rings"],
  [/microwave popcorn \(golden sizzle\)/i, "butter popcorn"],
  [/max protein chips/i, "baked multigrain protein chips"],
  // noodles, soups, ready meals
  [/2-minute masala noodles/i, "masala instant noodles"],
  [/nutri-licious atta noodles/i, "wholewheat instant noodles"],
  [/nutri-licious oats noodles/i, "oats instant noodles"],
  [/cuppa mania cup noodles/i, "cup noodles in a plain unprinted paper cup"],
  [/yippee magic masala noodles/i, "masala instant noodles"],
  [/\(dry pack\)/i, "(dry)"],
  [/ready to eat /i, ""],
  // cereals
  [/corn flakes original/i, "corn flakes"],
  [/chocos/i, "chocolate wheat-scoop cereal"],
  [/special k/i, "toasted rice-and-wheat flake cereal"],
  [/froot loops/i, "colourful fruit-flavoured cereal rings"],
  // dairy
  [/taaza toned milk|slim n trim skimmed milk|shakti standardised milk|gold full cream milk/i, "milk"],
  [/\((blue|green|orange) packet\)/i, ""],
  [/kool flavoured milk \(kesar \/ badam \/ elaichi\)/i, "kesar-badam flavoured milk"],
  [/mithai mate condensed milk/i, "sweetened condensed milk"],
  [/masti dahi/i, "dahi (set curd)"],
  [/masti spiced buttermilk/i, "spiced buttermilk"],
  [/malai paneer/i, "paneer block"],
  // chocolate & candy
  [/dairy milk silk/i, "a broken bar of thick silky milk chocolate"],
  [/dairy milk fruit & nut/i, "a broken bar of milk chocolate with raisins and almonds"],
  [/dairy milk/i, "a broken bar of milk chocolate"],
  [/5 star/i, "a caramel-nougat chocolate bar cut to show the caramel"],
  [/perk/i, "a chocolate-coated wafer bar"],
  [/gems/i, "colourful sugar-coated chocolate buttons"],
  [/fuse/i, "a peanut-caramel chocolate bar cut in half"],
  [/bournville rich cocoa 50%/i, "a broken bar of 50% dark chocolate"],
  [/choclairs gold \(eclairs\)/i, "unwrapped caramel eclairs with chocolate centres"],
  [/kitkat \(2 finger\)/i, "two chocolate-coated wafer fingers, one snapped"],
  [/munch/i, "a chocolate-coated crunchy wafer bar"],
  [/milkybar/i, "a white chocolate bar"],
  [/bar-one/i, "a nougat-caramel chocolate bar"],
  [/snickers bar/i, "a peanut-caramel-nougat chocolate bar cut in half"],
  [/galaxy smooth milk chocolate/i, "a smooth milk chocolate bar"],
  [/dark chocolate 55%/i, "a broken bar of 55% dark chocolate"],
  [/ferrero rocher/i, "hazelnut-wafer chocolate pralines, unwrapped, one cut open"],
  [/kinder joy/i, "a small chocolate-and-cream dessert cup with two wafer balls"],
  [/alpenliebe caramel candy/i, "unwrapped caramel hard candies"],
  [/melody toffee/i, "unwrapped chocolate-filled caramel toffees"],
  // spreads & sauces
  [/schezwan chutney/i, "red schezwan chutney"],
  [/mixed fruit jam/i, "mixed fruit jam"],
  [/fresh tomato ketchup/i, "tomato ketchup"],
  [/hot & sweet tomato chilli sauce/i, "sweet chilli tomato sauce"],
  // drinks
  [/coca-cola \(regular\)|pepsi \(regular\)|thums up cola|mcdonald's coke \(medium\)|coke \(medium\)/i, "dark cola with ice and bubbles"],
  [/sprite \(regular\)/i, "clear lemon-lime soda with ice"],
  [/fanta orange/i, "orange soda with ice"],
  [/mountain dew/i, "pale yellow-green citrus soda with ice"],
  [/bovonto/i, "dark grape-flavoured soda with ice"],
  [/appy fizz/i, "sparkling apple drink"],
  [/maaza mango drink|frooti mango drink|slice mango drink/i, "thick mango drink"],
  [/aamras/i, "thick mango aamras"],
  [/aam panna/i, "green raw-mango aam panna"],
  [/club soda/i, "sparkling soda water"],
  [/red bull energy drink|monster energy \(original green\)|sting energy drink/i, "a pale gold energy drink over ice"],
  [/red bull sugar free|monster ultra \(zero sugar\)/i, "a pale sugar-free energy drink over ice"],
  [/gatorade sports drink/i, "a blue sports drink"],
  [/glucon-d powder/i, "glucose drink powder"],
  [/nescafé ready-to-drink cold coffee \(can\)/i, "cold coffee"],
  [/frappuccino/i, "blended iced coffee topped with whipped cream"],
  [/krushers \(chocolate\)/i, "thick chocolate shake"],
  [/devil's own \(chocolate cold coffee\)/i, "thick chocolate cold coffee"],
  [/café frappé \(cold coffee\)/i, "frothy cold coffee"],
  [/bournvita powder/i, "malted chocolate drink powder"],
  [/women's horlicks powder|horlicks classic malt powder/i, "malted drink powder"],
  [/horlicks protein\+ powder/i, "chocolate protein drink powder"],
  [/complan powder|protinex original powder|ensure \(abbott\) powder/i, "nutrition drink powder"],
  // protein
  [/raw whey protein \(unflavoured\)/i, "unflavoured whey protein powder"],
  [/biozyme performance whey|whey gold \(isolate\)|gold standard 100% whey|impact whey protein|avvatar whey protein|whey protein concentrate 80%|perform whey protein/i, "chocolate whey protein powder"],
  [/mass gainer xxl/i, "chocolate mass-gainer powder"],
  [/20 g protein bar|10 g protein bar|max protein daily bar \(10 g\)|max protein active bar \(20 g\)|protein bar$/i, "protein bar, unwrapped, cut in half"],
  [/protein wafer bar/i, "protein wafer bar, unwrapped"],
  [/multigrain energy bar/i, "multigrain energy bar, unwrapped"],
  [/protein milkshake/i, "chocolate protein milkshake"],
  [/soya chunks \(dry\)/i, "dry soya chunks"],
  // frozen & meats
  [/smiles \(fried\)/i, "smiley-face potato bites"],
  // ice cream
  [/tricone/i, "chocolate-dipped ice-cream cone"],
  [/chocobar/i, "a chocolate-coated vanilla ice-cream bar on a stick"],
  [/cornetto double chocolate/i, "a chocolate ice-cream cone with a chocolate tip"],
  [/magnum/i, "a thick chocolate-coated ice-cream bar on a stick, one bite taken"],
  [/feast chocolate/i, "a chocolate-coated ice-cream bar with a chocolate core"],
  [/frozen dessert tub \(vanilla\)/i, "vanilla ice cream scooped into a bowl"],
  [/vanilla royale ice cream/i, "vanilla ice cream scoops"],
  // chains
  [/mcaloo tikki/i, "aloo tikki"],
  [/mcveggie/i, "crumbed veggie-patty"],
  [/mcchicken/i, "crumbed chicken-patty"],
  [/chicken maharaja mac/i, "tall double-decker grilled chicken burger"],
  [/veg maharaja mac/i, "tall double-decker veggie burger"],
  [/filet-o-fish/i, "fish fillet burger with cheese in a steamed bun"],
  [/mcspicy fried chicken/i, "spicy crispy fried chicken"],
  [/mcspicy/i, "spicy crispy"],
  [/mcegg/i, "steamed egg"],
  [/chicken mcgrill/i, "grilled chicken burger"],
  [/big spicy paneer wrap/i, "spicy crispy paneer wrap"],
  [/chicken mcnuggets/i, "chicken nuggets"],
  [/mcflurry oreo/i, "soft-serve vanilla with crushed chocolate cookies in a plain white cup"],
  [/veg mcpuff/i, "veg puff pastry"],
  [/mccafé /i, ""],
  [/hot & crispy chicken/i, "crispy fried chicken"],
  [/original recipe chicken/i, "classic fried chicken"],
  [/smoky grilled chicken/i, "smoky grilled chicken"],
  [/classic zinger burger/i, "crispy fried chicken fillet burger"],
  [/veg zinger burger/i, "crispy veggie-patty burger"],
  [/chicken longer burger/i, "long sub-style crispy chicken burger"],
  [/rice bowlz/i, "rice bowl"],
  [/biryani bucket/i, "biryani in a bowl"],
  [/chicken whopper/i, "large flame-grilled chicken burger"],
  [/veg whopper/i, "large flame-grilled veggie burger"],
  [/veg surprise/i, "veggie burger"],
  [/paneer royale/i, "crispy paneer burger"],
  [/crunchwrap supreme/i, "grilled hexagonal crunch wrap, cut to show layers"],
  [/moburg \(chicken momo burger\)/i, "momo-patty burger"],
  [/pizza mania \(onion \/ tomato\)/i, "small onion-and-tomato pizza"],
  [/choco lava cake/i, "chocolate lava cake, broken open with molten centre"],
  [/pasta italiano \(white\)/i, "white-sauce pasta"],
  [/taco mexicana \(veg\)/i, "folded veg taco"],
  [/potato cheese shots \/ wedges/i, "potato wedges"],
  [/burger pizza/i, "pizza burger (a mini pizza between buns)"],
  [/sub \(6 inch\)/i, "6-inch sub sandwich, cut to show the filling"],
  [/sauce \(mayo \/ chipotle \/ sweet onion\)/i, "sub sauce (a creamy dip)"],
  [/veggie delite/i, "veggie"],
  [/signature hot chocolate/i, "hot chocolate"],
  [/\(tall\)|\(regular\)/i, ""],
  [/hotel /i, "restaurant-style "],
  [/\((a2b \/ saravana bhavan|a2b \/ sweet stall)\)/i, ""],
  [/, sweeter/i, ""],
];

function esc(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
const BRAND_RE = new RegExp(`(^|\\s|\\()(${BRANDS.slice().sort((a, b) => b.length - a.length).map(esc).join("|")})(?=$|\\s|\\)|,)`, "gi");

/** Brand-free visual name for a food. */
function genericName(food) {
  let s = food.name;
  for (const [re, to] of TM) s = s.replace(re, to);
  s = s.replace(BRAND_RE, "$1");
  return s.replace(/\(\s*\)/g, "").replace(/\s{2,}/g, " ").replace(/\s+,/g, ",").replace(/^[\s,–-]+|[\s,–-]+$/g, "").trim();
}

module.exports = { genericName, BRANDS };
